source 'https://rubygems.org'

# Provide a wrapper for PostgreSQL
gem 'pg'

# Provide a reliable and fast Ruby wrapper for libcurl
gem 'curb'

# Analyze code in order to find code smells
gem 'reek', group: 'test'

# Provide a complete library for unit testing
gem 'rspec' group: 'test'
