<?php

/*
 * Hi, i'm GiveawayssBot and i'm here to create and manage giveaways on Telegram.
   Click on /start to show what i can do.
 * start - Show the menu
 * create - Create a new giveaway
 * join - Join a giveaway
 * browse - Show all the giveaways you've joined 
 * help - Get help using me
 * about - Get info about me and my creators
 */


$localization = [];

$localization['languages'] = [
    'en' => '🇬🇧 English',
    'it' => '🇮🇹 Italiano',
    'fi' => '🇫🇮 Suomi',
    'br' => '🇧🇷 Brazil',
    'ru' => '🇷🇺 Russian'
];

$localization['en'] = [
    'Welcome_Msg' => "Welcome to GiveawayBot 🎰.
Choose a language to begin:",
    'Menu_Msg' => 'GiveawayBot let you create, join and manage giveaways on Telegram.
Select an option:',
    'Join_Msg' => 'Enter the giveaway hashtag you want join:',
    'Help_Msg' => 'These instructions will <b>guide you to use me.</b>

A giveaway is a promotion or contest in which prizes are given away.
This bot provides <b>two types</b> of giveaways:
<code>JoinIn</code>: Each member has the same chance of winning.
<code>ShareIt</code>: Each member increases chance of winning inviting other people to the giveaway.

You only have to join one of them for a chance to win great prizes: click on an invite link or press Join button and follow the instructions.
If you joined it, look the details by pressing <code>Browse</code> button on the menu. Anyway if you won you\'ll receive a notification with your prize.
If you want to create a giveaway, press <code>Create</code> button in the menu and follow the instructions; at the end you\'ll receive the link to share it. The winners will be chosen randomly and the bot will send them a notification containing the key.
Click /start to return to the menu.
If you experience problems click /start to reset the bot or contact @danyspin97.

<b>WE DO NOT PROVIDE WARRANTY FOR THE GIVEAWAYS. ONLY THE OWNER ADDS THE KEYS OF THE PRIZES AND WE DO NOT PROVIDE RELIABILITY FOR WHO USE THIS BOT.</b>
<i>Thank you for your attention and good luck.</i>
<code>WiseDragonStd</code>🐉',
    'About_Msg' => 'This bot is written in php and ruby. It has been developed by <code>WiseDragonStd</code>🐉 team and uses HadesWrapper.
The code will be released as open source in early 2017.
For updates follow @WiseDragonStd channel.',
    'Register_Msg' => 'Welcome to the giveaway setup. Select one of the following types:
<code>JoinIn</code>: Each member has the same chance of winning.
<code>ShareIt</code>: Each member increases chance of winning inviting other people to the giveaway.',
    'EnteringTitle_Msg' => 'Enter the giveaway title:',
    'EnteringHashtag_Msg' => 'Enter a hashtag for this giveaway or skip. A giveaway can be joined inserting the hashtag after pressing <code>Join</code> button.',
    'EnteringDescription_Msg' => 'Enter a description for the giveaway:',
    'EnteringMaxparticipants_Msg' => 'Enter the MAX members allowed to join or skip for no limits:',
    'EnteringDate_Msg' => 'Enter the life (in days) of your giveaway:
(Enter a number between 3-40)',
    'EnteringFirstPrize_Msg' => 'Now you\'ll start creating the prizes for the current giveaway.
I\'ll prompt you all the info about the current prize, then you\'ll se a summary where you can add more prizes.',
    'EnteringPrizeName_Msg' => 'Enter the prize name:',
    'EnteringPrizeValue_Msg' => 'Enter how much this prize worth in the form 29.99€. You can use your own currency, if it isn\'t allowed you will choose it from a list:',
    'EnteringPrizeType_Msg' => 'Select prize type:',
    'EnteringPrizeCurrency_Msg' => 'Select a currency:',
    'EnteringPrizeKey_Msg' => 'Enter a key for this prize. You cannot modify the key after entering it, so please pay attention.
This Key will be sent to winner at the end of the giveaway.
It is securely stored on a database.',
    'EditTitle_Msg' => 'Enter the new <b>title</b>:',
    'EditHashtag_Msg' => 'Enter the new <b>hashtag</b>:',
    'EditDescription_Msg' => 'Enter the new <b>description</b>:',
    'EditDate_Msg' => 'Enter the new duration of the giveaway:
(Enter a number between 3-40)',
    'EditPrizeName_Msg' => 'Enter a new prize name:',
    'EditPrizeType_Msg' => 'Enter a new prize type:',
    'Title_Msg' => '<b>Title: </b>',
    'Hashatag_Msg' => '<b>Hashtag: </b>',
    'Maxparticipants_Msg' => '<b>MAX members allowed: </b>',
    'Description_Msg' => '<b>Description: </b>',
    'Date_Msg' => '<b>Date: </b>',
    'NewTitle_Msg' => '<b>New title: </b>',
    'NewHashtag_Msg' => '<b>New hashtag: </b>',
    'NewDescription_Msg' => '<b>New description: </b>',
    'NewDate_Msg' => '<b>New date: </b>',
    'PrizeName_Msg' => '<b>Prize name: </b>',
    'PrizeValue_Msg' => '<b>Value: </b>',
    'ValueNoCurrency_Msg' => '<b>Incomplete value: </b>',
    'PrizeKey_Msg' => '<b>Key: </b>',
    'PrizeType_Msg' => '<b>Type: </b>',
    'NewValue_Msg' => '<b>New value: </b>',
    'NewValueNoCurrency_Msg' => '<b>New incomplete value: </b>',
    'EditPrizeCurrency_Msg' => '<b>New value: </b>',
    'TitleLenght_Msg' => 'The title inserted is too short. Please insert a new one longer than 5 characters.',
    'ValidHashtag_Msg' => 'The hashtag inserted is not valid, please re-insert it.',
    'DuplicatedHashtag_Msg' => 'The hashtag entered is already used, please enter a new one.',
    'HashtagSkipped_Msg' => '<b>Hashtag:</b> <i>Skipped</i>.',
    'DescriptionSkipped_Msg' => '<b>Description:</b> <i>no description</i>.',
    'MaxparticipantsNotValid_Msg' => 'The MAX members allowed is not valid. Please insert a new one.',
    'MaxparticipantsInfinite_Msg' => '<b>Max members:</b> <i>no limit</i>.',
    'DateNotValid_Msg' => 'The date inserted is not valid, please insert a number between 3-40.',
    'ValueNotValid_Msg' => 'Please insert a valid value.',
    'NewValueNotValid_Msg' => 'The new value is not valid, please insert a new one.',
    'CancelGiveawayPrompt_Msg' => 'Are you really sure you want to cancel the setup of this giveaway?
It cannot be undone and all data inserted will be lost.',
    'ShowHashtagMissing_Msg' => 'You should insert the giveaway hashtag:',
    'ClosedGiveawayWarn_Msg' => '<b>The requested giveaway is closed.</b>',
    'NoGiveawayWarn_Msg' => '<b>Giveaway not found</b>',
    'MaxParticipants_Msg' => 'The giveaway has reached the members limit.',
    'JoinedSuccess_Msg' => 'You joined this giveaway!',
    'CancelSuccess_Msg' => 'You deleted the giveaway  ¯\_(ツ)_/¯',
    'MissingHashtagWarn_Msg' => 'You should insert an hashtag:',
    'StatsEmpty_Msg' => 'Sorry, there are no giveaways to browse.',
    'Value_Msg' => 'For a value of ',
    'Owned_Msg' => '<code>Owned</code>',
    'Joined_Msg' => '<code>Joined</code>',
    'Closed_Msg' => '<code>Closed</code>',
    'LastDay_Msg' => '<code>Last day</code>',
    'UserError_Msg' => '<b>The giveaway or the user you\'re searching for doesn\'t exist.</b>',
    'AlreadyIn_Msg' => '<b>You already joined the giveaway.</b>',
    'ReferralLink_Msg' => 'This is your referral link, copy it and share with your friends:',
    'AfterCreation_Msg' => 'Giveaway successfully created!',
    'Hash_Msg' => '<b>Hashtag: </b>',
    'Type_Msg' => '<b>Type: </b>',
    'MPValue_Msg' => '<b>MAX members allowed: </b>',
    'EndDate_Msg' => '<b>End date: </b>',
    'Desc_Msg' => '<b>Description: </b>',
    'GiveawayPrizes_Msg' => '<b>Number of prizes: </b>',
    'Undefined_Msg' => '<i>Not defined</i>',
    'TotalValue_Msg' => '<b>For a value of: </b>',
    'JoinLabel_Msg' => 'Join ',
    'Unlimited_Msg' => '<i>Unlimited</i>',
    'Inception_Msg' => '<b>You created this giveaway. You can\'t join it ;)</b>',
    'NowLabel_Msg' => ' now and win wonderful prizes!',
    'UnavailableDesc_Msg' => 'No description avaible',
    'Days_Msg' => 'days',
    'Menu_Button' => '📜 Menu',
    'Register_Button' => '🖍 Create',
    'Show_Button' => '🕹 Browse',
    'Language_Button' => '🌐 Language',
    'standard_Button' => '➡️ JoinIn',
    'cumulative_Button' => '↪️ ShareIt',
    'Back_Button' => '🔙 Back',
    'Skip_Button' => '🔜 Skip',
    'Confirm_Button' => '✔️ Confirm',
    'Infinite_Button' => '⚪️ No limit',
    'EditTitle_Button' => '📝 Edit title',
    'EditHashtag_Button' => '#⃣ Edit hashtag',
    'EditMaxparticipants_Button' => '🔢 Edit members',
    'EditDescription_Button' => '📝 Edit description',
    'EditDate_Button' => '📅 Edit date',
    'DeleteHashtag_Button' => '❎ Delete hashtag',
    'DeleteDescription_Button' => '❎ Delete description',
    'AddHashtag_Button' => '#⃣ Add hashtag',
    'AddDescription_Button' => '📝 Add description',
    'AddMaxparticipants_Button' => '🔢 Add members limit',
    'ConfirmGiveaway_Button' => '✔️ Confirm',
    'ConfirmPrizes_Button' => '✔️ Confirm prizes',
    'AddPrize_Button' => '➕ Add prize',
    'CancelGiveaway_Button' => '✖️ Cancel giveaway',
    'EditPrizeName_Button' => '📝 Edit name',
    'EditPrizeType_Button' => '🎲 Edit type',
    'EditPrizeValue_Button' => '💲 Edit value',
    'EditPrizeCurrency_Button' => '💱 Edit currency',
    'DeletePrize_Button' => '❌ Delete',
    'Prizes_Button' => '🎁 All prizes',
    'Type1_Button' => '🎮 Videogame key',
    'Type2_Button' => '📃 Coupon',
    'Type3_Button' => '📄 Gift Card',
    'Type4_Button' => '🔑 Other',
    'Join_Button' => '#⃣ Join',
    'Cancel_Button' => '🚫 Cancel',
    'Help_Button' => '*⃣ Help',
    'About_Button' => 'ℹ️ About',
    'Source_Button' => '📖 Source',
    'Updates_Button' => '❕ Updates',
    'ClosedGiveaway_Msg' => '<b>The requested giveaway is closed.</b>',
    'standard_AnswerCallback' => 'JoinIn',
    'cumulative_AnswerCallback' => 'ShareIt',
    'HashtagSkipped_AnswerCallback' => 'Hashtag skipped',
    'DescriptionSkippet_AnswerCallback' => 'No description',
    'MaxparticipantsInfinite_AnswerCallback' => 'No limit',
    'Language_AnswerCallback' => 'Choose language',
    'SameLanguage_AnswerCallback' => 'Same language',
    '€_AnswerCallback' => 'Euro',
    '$_AnswerCallback' => 'Dollar',
    'Register_InlineQuery' => 'Register',
    'SwitchPM_InlineQuery' => 'Create or browse',
    'ShareLink_Button' => 'Share',
    'ShowLink_Button' => 'Show link',
    'UndefinedHashtag_Msg' => '<i>No hashtag</i>',
    'BrowsePrize_Button' => 'Browse Prizes',
    'GiveawayEnded_Msg' => 'The giveaway has already ended.',
    'GiveawayNotExists_Msg' => 'The giveaway does not exists.',
    'OtherPrizes_Msg' => '<i>And others...</i>',
    'JoinedSucces_AnswerCallback' => 'Joined',
    'CreatorJoining_AnswerCallback' => 'You are the creator',
    'GiveawayEnded_AnswerCallback' => 'The giveaway has ended',
    'PrizesNumber_Msg' => 'Prizes',
    'JoinInsertNewHashtag_Msg' => 'Please insert a new hashtag.',
    'NoGiveawayToShow_AnswerCallback' => 'No giveaway to browse',
    'NoRoom_AnswerCallback' => 'This giveaways has reached the max',
<<<<<<< HEAD
    'AlreadyJoined_AnswerCallback' => 'You already joined this giveaway',
    'StartBot_AnswerCallback' => 'Start the bot first',
=======
>>>>>>> ba84961ae7ba1ac09ca68a2426f4cdc223af0be7
    'it' => 'Italian',
    'es' => 'Spanish',
    'fr' => 'French',
    'de' => 'German',
    'pt' => 'Portugues',
    'br' => 'Brazil',
    'ru' => 'Russian',
    'fa' => 'Farsi(Persian)',
    'hi' => 'Hindi',
    'fi' => 'Finnish',
    'nl' => 'Dutch',
    'zh' => 'Chinese',
];

$localization['it'] = [
    'Welcome_Msg' => 'Welcome to GiveawaysBot 🎰.
Choose a language to begin:',
    'Menu_Msg' => 'GiveawaysBot ti permette di creare, partecipare e gestire giveaways direttamente da Telegram. Per continuare seleziona un\'opzione:',
    'Join_Msg' => 'Inserisci l\'hashtag del giveaway in cui vuoi entrare:',
    'Help_Msg' => 'Con queste informazioni <b>imparerai ad usarmi.</b>
Un giveaway è un contest nel quale vengono donati premi, tramite scelta random tra i partecipanti.
Questo bot supporta <b>due tipi</b> di giveaway:
<code>JoinIn</code>: Ogni partecipante ha la stessa probabilità di vincere.
<code>ShareIt</code>: Le chance di ogni partecipante aumentano invitando altre persone a partecipare al giveaway. 
Devi solo entrare in un giveaway per potere vincere randiosi premi: premi su un link oppure usa il bottone “Entra” e segui le istruzioni.
Se sei entrato in un giveaway, guarda i dettagli premendo il bottone <code> Sfoglia </code> presente nel menu. Se vincerai, ti avviserò del premio che devi ricevere.
Se vuoi creare un giveaway, premi il bottone <code> Crea </code> presente nel menu e segui le istruzioni; a registrazione completa, riceverai il link per condividerlo. I vincitori verranno scelti a caso e il bot li avviserà con un messaggio contenente la chiave.
Scrivi /start per tornare al menu.
Se ricontri problemi, scrivi /start per resettare il bot oppure contatta @danyspin97. <i> Resettando il bot cancellerai l\' operazione attuale ma non perderai alcun dato.</i>
<b>ATTENZIONE: NOI NON GARANTIAMO PER I GIVEAWAY. SOLO IL PROPRETARIO DEL GIVEAWAY INSERISCE LE CHIAVI DEI PREMI E NON GARANTIAMO PER GLI UTILIZZATORI DI QUESTO BOT.</b>
<i>Grazie per la tua attenzione e buona fortuna!</i>
<code>WiseDragonStd</code>🐉',
    'About_Msg' => 'Questo bot è scritto in php e ruby. È stato sviluppato da  <code>WiseDragonStd</code>🐉 e usa HadesWrapper.
Il codice verrà rilasciato come open source gli inizi del 2017.
Per ulteriori news segui: @WiseDragonStd channel.',
    'Register_Msg' => 'Benvenuto nel setup del giveaway. Seleziona una delle opzioni:
<code>JoinIn</code>: Ogni partecipante ha la stessa probabilità di vincere..
<code>ShareIt</code>: Le chance di ogni partecipante aumentano invitando altre persone a partecipare al giveaway.',
    'EnteringTitle_Msg' => 'Inserisci il titolo del giveaway:',
    'EnteringHashtag_Msg' => 'Inserisci un hashtag per il giveaway o salta. Inserendo un hashtag gli utenti potranno entrare usando l\'hashtag dopo aver premuto il bottone <code>Join</code> nel menu.',
    'EnteringDescription_Msg' => 'Inserisci una descrizione del giveaway:',
    'EnteringMaxparticipants_Msg' => 'Inserisci il numero massimo di utenti partecipanti al giveaway oppure salta per non impostare alcun limite:',
    'EnteringDate_Msg' => 'Inserisci la durata (in giorni) del giveaway:
(Deve essere un numero compreso tra 3 e 40)',
    'EnteringFirstPrize_Msg' => 'Ora incomincerai a creare i premi per questo giveawayNow you\'ll start creating the prizes for the current giveaway.
Ti chiederò tutte le info riguardanti il premio corrente, poi ti mostrerò un sommario dal quale potrai aggiungere più premi',
    'EnteringPrizeName_Msg' => 'Inserisci il nome del premio:',
    'EnteringPrizeValue_Msg' => 'Inserisci il valore del premio, ad esempio <b>29.99€</b>. Puoi usare la tua moneta, se non è supportata potrai scegliere da una lista:',
    'EnteringPrizeType_Msg' => 'Seleziona il tipo di premio:',
    'EnteringPrizeCurrency_Msg' => 'Seleziona una moneta:',
    'EnteringPrizeKey_Msg' => 'Inserisci una chiave per il premio. Non potrai modificarla, quinid presta attenzione.
Questa chiave verrà inviata al vincitore alla fine del giveaway.
È conservata in un dataqbase sicuro.',
    'EditTitle_Msg' => 'Inserisci il nuovo <b>titolo</b>:',
    'EditHashtag_Msg' => 'Inserisci il nuovo <b>hashtag</b>:',
    'EditDescription_Msg' => 'Inserisci la nuova <b>descrizione</b>:',
    'EditDate_Msg' => 'Inserisci la nuova durata del giveaway:
(Deve essere un numero compreso tra 3 e 40)',
    'EditPrizeName_Msg' => 'Inserisci il nuovo nome del premio:',
    'EditPrizeType_Msg' => 'Inserisci il nuovo titolo del premio:',
    'Title_Msg' => '<b>Titolo: </b>',
    'Hashatag_Msg' => '<b>Hashtag: </b>',
    'Maxparticipants_Msg' => '<b>Numero massimo di membri: </b>',
    'Description_Msg' => '<b>Descrizione: </b>',
    'Date_Msg' => '<b>Data: </b>',
    'NewTitle_Msg' => '<b>Nuovo titolo: </b>',
    'NewHashtag_Msg' => '<b>Nuovo hashtag: </b>',
    'NewDescription_Msg' => '<b>Nuova descrizione: </b>',
    'NewDate_Msg' => '<b>Nuova data: </b>',
    'PrizeName_Msg' => '<b>Nome del premio:: </b>',
    'PrizeValue_Msg' => '<b>Valore: </b>',
    'ValueNoCurrency_Msg' => '<b>Incomplete value: </b>',
    'PrizeKey_Msg' => '<b>Chiave: </b>',
    'PrizeType_Msg' => '<b>Tipo: </b>',
    'NewValue_Msg' => '<b>Nuovo valore: </b>',
    'NewValueNoCurrency_Msg' => '<b>Nuovo valore imparziale: </b>',
    'EditPrizeCurrency_Msg' => '<b>Nuovo valore: </b>',
    'TitleLenght_Msg' => 'Il titolo inserito è troppo corto. Inserisci un titolo con più di 5 caratteri.',
    'ValidHashtag_Msg' => 'L\'hashtag inserito non è valido; per favore, reinseriscilo.',
    'DuplicatedHashtag_Msg' => 'L\'hashtag inserito non è disponibile, inseriscine un altro.',
    'HashtagSkipped_Msg' => '<b>Hashtag:</b> <i>Saltato</i>.',
    'DescriptionSkipped_Msg' => '<b>Descrizione:</b> <i>nesusna descrizione</i>.',
    'MaxparticipantsNotValid_Msg' => 'Il valore del limite di membri permesso non è valido. Per favore, inseriscine uno nuovo.',
    'MaxparticipantsInfinite_Msg' => '<b>Limite membri:</b> <i>nessun limite</i>.',
    'DateNotValid_Msg' => 'La data di scadenza inserita non è valida, per favore inserisci un numero compreso tra 3 e 40.',
    'ValueNotValid_Msg' => 'Per favore, inserisci un valore valido.',
    'NewValueNotValid_Msg' => 'Il nuovo valore non è valido, per favore inseriscine un altro.',
    'CancelGiveawayPrompt_Msg' => 'Sei davvero sicuro di voler cancellare il setup di questo giveaway?
Non può essere annullato e tutti i dati inseriti saranno persi per sempre.',
    'ShowHashtagMissing_Msg' => 'Dovresti inserire l\'hashtag del giveaway:',
    'ClosedGiveawayWarn_Msg' => '<b>Il giveaway richiesto è chiuso.</b>',
    'NoGiveawayWarn_Msg' => '<b>Il giveaway richiesto non è stato trovato</b>',
    'MaxParticipants_Msg' => 'Mi dispiace, ma il giveaway è pieno.',
    'JoinedSuccess_Msg' => 'Ti sei registrato a questo giveaway!',
    'CancelSuccess_Msg' => 'Hai eliminato il giveaway  ¯\_(ツ)_/¯',
    'MissingHashtagWarn_Msg' => 'Inserisci un hashtag:',
    'StatsEmpty_Msg' => 'Mi spiace, ma non ti sei registrato in nessun giveaway',
    'Value_Msg' => 'Per un valore di ',
    'Owned_Msg' => '<code>Posseduto</code>',
    'Joined_Msg' => '<code>Registrato</code>',
    'Closed_Msg' => '<code>Chiuso</code>',
    'LastDay_Msg' => '<code>Ultimo giorno</code>',
    'UserError_Msg' => '<b>Il giveaway o l\'utente che stai cercando non esiste.</b>',
    'AlreadyIn_Msg' => '<b>Hai già preso parte al giveaway.</b>',
    'ReferralLink_Msg' => 'Questo è il tuo link d\'invito, copialo e condividilo.',
    'AfterCreation_Msg' => 'Giveaway creato correttamente!',
    'Hash_Msg' => '<b>Hashtag: </b>',
    'Type_Msg' => '<b>Tipo: </b>',
    'MPValue_Msg' => '<b>Partecipanti consentiti: </b>',
    'EndDate_Msg' => '<b>Durata: </b>',
    'Desc_Msg' => '<b>Descrizione: </b>',
    'GiveawayPrizes_Msg' => '<b>Numero di premi: </b>',
    'Undefined_Msg' => '<i>Non definito</i>',
    'TotalValue_Msg' => '<b>Per un valore totale di: </b>',
    'JoinLabel_Msg' => 'Entra ',
    'Unlimited_Msg' => '<i>Illimitato</i>',
    'NowLabel_Msg' => ' ora e vinci fantastici premi!',
    'UndefinedHashtag' => '</b>Hashtag non in uso<b>',
    'Days_Msg' => 'Giorni',
    'Inception_Msg' => '<b>Non puoi partecipare a un giveaway da te creato.</b>',
    'UnavailableDesc_Msg' => 'Nessuna descrizione disponibile',
    'Prizes_Button' => 'Tutti i premi',
    'Type1_Button' => 'Videogioco',
    'Type2_Button' => 'Coupon',
    'Type3_Button' => 'Gift Card',
    'Type4_Button' => 'Altro',
    'AddPrize_Button' => 'Aggiungi premio',
    'EditPrizeName_Button' => 'Modifica nome',
    'EditPrizeType_Button' => 'Modifica tipo',
    'EditPrizeValue_Button' => 'Modifica valore',
    'EditPrizeCurrency_Button' => 'Modifica moneta',
    'DeletePrize_Button' => 'Cancella',
    'Menu_Button' => '📜 Menu',
    'Register_Button' => '🖍 Crea',
    'Show_Button' => '🕹 Sfoglia',
    'Language_Button' => '🌐 Lingua',
    'standard_Button' => '➡️ JoinIn',
    'cumulative_Button' => '↪️ ShareIt',
    'Back_Button' => '🔙 Indietro',
    'Skip_Button' => '🔜 Salta',
    'Confirm_Button' => '✔️ Conferma',
    'Infinite_Button' => '⚪️ Nessun limite',
    'EditTitle_Button' => '📝 Modifica il titolo',
    'EditHashtag_Button' => '#⃣ Modifica l\'hashtag',
    'EditMaxparticipants_Button' => '🔢 Modifica numero membri',
    'EditDescription_Button' => '📝 Modifica la descrizione',
    'EditDate_Button' => '📅 Modifica la data',
    'DeleteHashtag_Button' => '❎ Cancella l\'hashtag',
    'DeleteDescription_Button' => '❎ Cancella ò la descrizione',
    'AddHashtag_Button' => '#⃣ Aggiungi un hashtag',
    'AddDescription_Button' => '📝 Aggiungi una descrizione',
    'AddMaxparticipants_Button' => '🔢 Aggiungi limite membri ',
    'ConfirmGiveaway_Button' => '✔️ Conferma',
    'ConfirmPrizes_Button' => '✔️ Conferma premi',
    'AddPrize_Button' => '➕ Aggiungi premio',
    'CancelGiveaway_Button' => '✖️ Cancella giveaway',
    'EditPrizeName_Button' => '📝 Modifica nome',
    'EditPrizeType_Button' => '🎲 Modifica tipo',
    'EditPrizeValue_Button' => '💲 Modifica valore',
    'EditPrizeCurrency_Button' => '💱 Cambia valuta',
    'DeletePrize_Button' => '❌ Elimina',
    'Prizes_Button' => '🎁 Tutti i premi',
    'Type1_Button' => '🎮 Chiave di un videogioco',
    'Type2_Button' => '📃 Coupon',
    'Type3_Button' => '📄 Carta regalo',
    'Type4_Button' => '🔑 Altro',
    'Join_Button' => '#⃣ Entra',
    'Cancel_Button' => '🚫 Cancella',
    'Help_Button' => '*⃣ Aiuto',
    'About_Button' => 'ℹ️ Info',
    'Source_Button' => '📖 Codice Sorgente',
    'Updates_Button' => '❕ Aggiornamenti',
    'ShareLink_Button' => 'Condividi',
    'ShowLink_Button' => 'Mostra link',
    'ClosedGiveaway_Msg' => '<b>Il giveaway richiesto è chiuso.</b>',
    'standard_AnswerCallback' => 'JoinIn',
    'cumulative_AnswerCallback' => 'ShareIt',
    'HashtagSkipped_AnswerCallback' => 'Hashtag saltato',
    'DescriptionSkippet_AnswerCallback' => 'Nessuna descrizione',
    'MaxparticipantsInfinite_AnswerCallback' => 'Nessun limite',
    'Language_AnswerCallback' => 'Scegli la lingua',
    'SameLanguage_AnswerCallback' => 'Stessa lingua',
    '€_AnswerCallback' => 'Euro',
    '$_AnswerCallback' => 'Dollaro',
    'Register_InlineQuery' => 'Registra',
    'SwitchPM_InlineQuery' => 'Crea or sfoglia',
    'BrowsePrize_Button' => 'Sfoglia Premi',
    'UndefinedHashtag_Msg' => 'No hashtag',
    'en' => 'Inglese',
    'it' => 'Italiano',
    'es' => 'Spagnolo',
    'fr' => 'Francese',
    'de' => 'Tedesco',
    'pt' => 'Portoghese',
    'ru' => 'Russo',
    'fi' => 'Finlandese',
    'fa' => 'Persiano',
    'hi' => 'Indiano',
    'nl' => 'Olandese',
    'zh' => 'Cinese',
];
/*

$localization['fi'] = [
    'Welcome_Msg' => "Welcome to GiveawayBot 🎰.
Choose a language to begin:",
    'Menu_Msg' => 'GiveawayBot let you create, join and manage giveaways on Telegram.
Select an option:',
    'Join_Msg' => 'Enter the giveaway hashtag you want join:',
    'Help_Msg' => 'These instructions will <b>guide you to use me.</b>

A giveaway is a promotion or contest in which prizes are given away.
This bot provides <b>two types</b> of giveaways:
<code>JoinIn</code>: Each member has the same chance of winning.
<code>ShareIt</code>: Each member increases chance of winning inviting other people to the giveaway.

You only have to join one of them for a chance to win great prizes: click on an invite link or press Join button and follow the instructions.
If you joined it, look the details by pressing <code>Browse</code> button on the menu. Anyway if you won you\'ll receive a notification with your prize.
If you want to create a giveaway, press <code>Create</code> button in the menu and follow the instructions; at the end you\'ll receive the link to share it. The winners will be chosen randomly and the bot will send them a notification containing the key.
Click /start to return to the menu.
If you experience problems click /start to reset the bot or contact @danyspin97.

<b>WE DO NOT PROVIDE WARRANTY FOR THE GIVEAWAYS. ONLY THE OWNER ADDS THE KEYS OF THE PRIZES AND WE DO NOT PROVIDE RELIABILITY FOR WHO USE THIS BOT.</b>
<i>Thank you for your attention and good luck.</i>
<code>WiseDragonStd</code>🐉',
    'About_Msg' => 'This bot is written in php and ruby. It has been developed by <code>WiseDragonStd</code>🐉 team and uses HadesWrapper.
The code will be released as open source in early 2017.
For updates follow @WiseDragonStd channel.',
    'Register_Msg' => 'Welcome to the giveaway setup. Select one of the following types:
<code>JoinIn</code>: Each member has the same chance of winning.
<code>ShareIt</code>: Each member increases chance of winning inviting other people to the giveaway.',
    'EnteringTitle_Msg' => 'Enter the giveaway title:',
    'EnteringHashtag_Msg' => 'Enter a hashtag for this giveaway or skip. A giveaway can be joined inserting the hashtag after pressing <code>Join</code> button.',
    'EnteringDescription_Msg' => 'Enter a description for the giveaway:',
    'EnteringMaxparticipants_Msg' => 'Enter the MAX members allowed to join or skip for no limits:',
    'EnteringDate_Msg' => 'Enter the life (in days) of your giveaway:
(Enter a number between 3-40)',
    'EnteringFirstPrize_Msg' => 'Now you\'ll start creating the prizes for the current giveaway.
I\'ll prompt you all the info about the current prize, then you'll se a summary where you can add more prizes.',
    'EnteringPrizeName_Msg' => 'Enter the prize name:',
    'EnteringPrizeValue_Msg' => 'Enter how much this prize worth in the form 29.99€. You can use your own currency, if it isn\'t allowed you will choose it from a list:',
    'EnteringPrizeType_Msg' => 'Select prize type:',
    'EnteringPrizeCurrency_Msg' => 'Select a currency:',
    'EnteringPrizeKey_Msg' => 'Enter a key for this prize. You cannot modify the key after entering it, so please pay attention.
This Key will be sent to winner at the end of the giveaway.
It is securely stored on a database.',
    'EditTitle_Msg' => 'Enter the new <b>title</b>:',
    'EditHashtag_Msg' => 'Enter the new <b>hashtag</b>:',
    'EditDescription_Msg' => 'Enter the new <b>description</b>:',
    'EditDate_Msg' => 'Enter the new duration of the giveaway:
(Enter a number between 3-40)',
    'EditPrizeName_Msg' => 'Enter a new prize name:',
    'EditPrizeType_Msg' => 'Enter a new prize type:',
    'Title_Msg' => '<b>Title: </b>',
    'Hashatag_Msg' => '<b>Hashtag: </b>',
    'Maxparticipants_Msg' => '<b>MAX members allowed: </b>',
    'Description_Msg' => '<b>Description: </b>',
    'Date_Msg' => '<b>Date: </b>',
    'NewTitle_Msg' => '<b>New title: </b>',
    'NewHashtag_Msg' => '<b>New hashtag: </b>',
    'NewDescription_Msg' => '<b>New description: </b>',
    'NewDate_Msg' => '<b>New date: </b>',
    'PrizeName_Msg' => '<b>Prize name: </b>',
    'PrizeValue_Msg' => '<b>Value: </b>',
    'ValueNoCurrency_Msg' => '<b>Incomplete value: </b>',
    'PrizeKey_Msg' => '<b>Key: </b>',
    'PrizeType_Msg' => '<b>Type: </b>',
    'NewValue_Msg' => '<b>New value: </b>',
    'NewValueNoCurrency_Msg' => '<b>New incomplete value: </b>',
    'EditPrizeCurrency_Msg' => '<b>New value: </b>',
    'TitleLenght_Msg' => 'The title inserted is too short. Please insert a new one longer than 5 characters.',
    'ValidHashtag_Msg' => 'The hashtag inserted is not valid, please re-insert it.',
    'DuplicatedHashtag_Msg' => 'The hashtag entered is already used, please enter a new one.',
    'HashtagSkipped_Msg' => '<b>Hashtag:</b> <i>Skipped</i>.',
    'DescriptionSkipped_Msg' => '<b>Description:</b> <i>no description</i>.',
    'MaxparticipantsNotValid_Msg' => 'The MAX members allowed is not valid. Please insert a new one.',
    'MaxparticipantsInfinite_Msg' => '<b>Max members:</b> <i>no limit</i>.',
    'DateNotValid_Msg' => 'The date inserted is not valid, please insert a number between 3-40.',
    'ValueNotValid_Msg' => 'Please insert a valid value.',
    'NewValueNotValid_Msg' => 'The new value is not valid, please insert a new one.',
    'CancelGiveawayPrompt_Msg' => 'Are you really sure you want to cancel the setup of this giveaway?
It cannot be undone and all data inserted will be lost.',
    'ShowHashtagMissing_Msg' => 'You should insert the giveaway hashtag:',
    'ClosedGiveawayWarn_Msg' => '<b>The requested giveaway is closed.</b>',
    'NoGiveawayWarn_Msg' => '<b>Giveaway not found</b>',
    'MaxParticipants_Msg' => 'Sorry but the giveaway has reached the MAX member allowed.',
    'JoinedSuccess_Msg' => 'You joined this giveaway!',
    'CancelSuccess_Msg' => 'You deleted the giveaway  ¯\_(ツ)_/¯',
    'MissingHashtagWarn_Msg' => 'You should insert an hashtag:',
    'StatsEmpty_Msg' => 'Sorry, you didn\'t join giveaways',
    'Value_Msg' => 'For a value of ',
    'Owned_Msg' => '<code>Owned</code>',
    'Joined_Msg' => '<code>Joined</code>',
    'Closed_Msg' => '<code>Closed</code>',
    'LastDay_Msg' => '<code>Last day</code>',
    'UserError_Msg' => '<b>The giveaway or the user you\'re searching for doesn\'t exist.</b>',
    'AlreadyIn_Msg' => '<b>You already joined the giveaway.</b>',
    'ReferralLink_Msg' => 'This is your referral link, copy it and share with your friends:',
    'AfterCreation_Msg' => 'Giveaway successfully created!',
    'Hash_Msg' => '<b>Hashtag: </b>',
    'Type_Msg' => '<b>Type: </b>',
    'MPValue_Msg' => '<b>MAX members allowed: </b>',
    'EndDate_Msg' => '<b>End date: </b>',
    'Desc_Msg' => '<b>Description: </b>',
    'GiveawayPrizes_Msg' => '<b>Number of prizes: </b>',
    'Undefined_Msg' => '<i>Not defined</i>',
    'TotalValue_Msg' => '<b>For a value of: </b>',
    'JoinLabel_Msg' => 'Join ',
    'Unlimited_Msg' => '<i>Unlimited</i>',
    'Inception_Msg' => '<b>You created this giveaway. You can\'t join it ;)</b>',
    'NowLabel_Msg' => ' now and win wonderful prizes!',
    'UnavailableDesc_Msg' => 'No description found',
    'Days_Msg' => 'days',

 */

$localization['fi'] = [
    'Welcome_Msg' => "Tervetuloa GiveawayBotiin ðŸŽ°.
Valitse kieli aloittaaksesi:",
    'Menu_Msg' => 'GiveawayBot antaa sinun luoda, osallistua ja hallita arvontoja Telegramissa.
Valitse vaihtoehto:',
    'Join_Msg' => 'Anna haluamasi arvonnan hashtag:',
    'Help_Msg' => 'NÃ¤mÃ¤ ohjeet <b>auttavat sinua kÃ¤yttÃ¤mÃ¤Ã¤n minua.</b>
Arvonta (giveaway) on tarjous tai kilpailu, jossa palkinnot jaetaan ilmaiseksi.
TÃ¤mÃ¤ botti tarjoaa <b>kahdenlaisia</b> arvontoja:
<code>JoinIn</code>: Jokaisella osallistujalla on samat mahdollisuudet voittaa.
<code>ShareIt</code>: Osallistuja lisÃ¤Ã¤ voittomahdollisuuksiaan kutsumalla muita osallistumaan.
Sinun tÃ¤ytyy liittyÃ¤ vain yhteen voidaksesi voittaa upeita palkintoja: klikkaa kutsulinkkiÃ¤ tai paina Liity ja seuraa ohjeita.
Jos liityit sellaiseen, katso lisÃ¤tietoja painamalla valikosta <code>Selaa</code>. Jos voitit, saat ilmoituksen palkinnostasi.
Jos haluat luoda arvonnan, paina valikosta <code>Luo</code> ja seuraa ohjeita; lopuksi saat linkin sen jakamiseen. Voittajat valitaan satunnaisesti ja botti lÃ¤hettÃ¤Ã¤ heille avaimen sisÃ¤ltÃ¤vÃ¤n ilmoituksen.
Klikkaa /start palataksesi valikkoon.
Jos ongelmia ilmenee, klikkaa /start nollataksesi botin tai ota yhteyttÃ¤ kÃ¤yttÃ¤jÃ¤Ã¤n @danyspin97.
<b>EMME ANNA TAKUUTA ARVONNOILLE. VAIN OMISTAJA LISÃ„Ã„ PALKINTOJEN AVAIMET JA EMME TAKAA BOTIN KÃ„YTTÃ„JIEN LUOTETTAVUUTTA.</b>
<i>Kiitos huomiostasi ja onnea.</i>
<code>WiseDragonStd</code>ðŸ‰',
    'About_Msg' => 'TÃ¤mÃ¤ botti on kirjoitettu php:lla ja rubyllÃ¤. Sen on kehittÃ¤nyt <code>WiseDragonStd</code>ðŸ‰-tiimi ja se kÃ¤yttÃ¤Ã¤ HadesWrapperia.
Koodi julkaistaan avoimena lÃ¤hdekoodina alkuvuodesta 2017.
Saadaksesi lisÃ¤tietoja seuraa kanavaa @WiseDragonStd.',
    'Register_Msg' => 'Tervetuloa arvonnan luontiin. Valitse yksi seuraavista tyypeistÃ¤:
<code>JoinIn</code>: Jokaisella osallistujalla on samat mahdollisuudet voittaa.
<code>ShareIt</code>: Osallistuja lisÃ¤Ã¤ voittomahdollisuuksiaan kutsumalla muita osallistumaan.',
    'EnteringTitle_Msg' => 'Anna arvonnan otsikko:',
    'EnteringHashtag_Msg' => 'Anna hashtag tÃ¤lle arvonnalle tai ohita. Arvontaan voi liittyÃ¤ painamalla <code>Join</code> ja syÃ¶ttÃ¤mÃ¤llÃ¤ hashtagin.',
    'EnteringDescription_Msg' => 'Anna kuvaus arvonnalle:',
    'EnteringMaxparticipants_Msg' => 'Anna osallistujien maksimimÃ¤Ã¤rÃ¤ tai ohita salliaksesi rajattomasti kÃ¤yttÃ¤jiÃ¤:',
    'EnteringDate_Msg' => 'Anna arvonnan kesto (pÃ¤iviÃ¤):
(SyÃ¶tÃ¤ luku vÃ¤liltÃ¤ 3-40)',
    'EnteringFirstPrize_Msg' => 'Nyt alat luoda palkintoja nykyiselle arvonnalle.
PyydÃ¤n sinulta kaikki tiedot nykyisestÃ¤ palkinnosta, sitten nÃ¤et yhteenvedon, jossa voit lisÃ¤tÃ¤ palkintoja.',
    'EnteringPrizeName_Msg' => 'SyÃ¶tÃ¤ palkinnon nimi:',
    'EnteringPrizeValue_Msg' => 'SyÃ¶tÃ¤ palkinnon arvo muodossa 29.99â‚¬. Voit kÃ¤yttÃ¤Ã¤ omaa valuuttaasi; jos se ei ole sallittu, valitset sen listalta:',
    'EnteringPrizeType_Msg' => 'Valitse palkinnon tyyppi:',
    'EnteringPrizeCurrency_Msg' => 'Valitse valuutta:',
    'EnteringPrizeKey_Msg' => 'SyÃ¶tÃ¤ avain tÃ¤lle palkinnolle. Et voi muuttaa avainta syÃ¶ttÃ¤misen jÃ¤lkeen, joten ole huolellinen.
Avain lÃ¤hetetÃ¤Ã¤n voittajalle arvonnan lopuksi.
Se tallennetaan turvallisesti tietokantaan.',
    'EditTitle_Msg' => 'Anna uusi <b>otsikko</b>:',
    'EditHashtag_Msg' => 'Anna uusi <b>hashtag</b>:',
    'EditDescription_Msg' => 'Anna uusi <b>kuvaus</b>:',
    'EditDate_Msg' => 'Anna arvonnan uusi kesto:
(SyÃ¶tÃ¤ luku vÃ¤liltÃ¤ 3-40)',
    'EditPrizeName_Msg' => 'Anna uuden palkinnon nimi:',
    'EditPrizeType_Msg' => 'Anna uuden palkinnon tyyppi:',
    'Title_Msg' => '<b>Otsikko: </b>',
    'Hashatag_Msg' => '<b>Hashtag: </b>',
    'Maxparticipants_Msg' => '<b>JÃ¤senten maksimimÃ¤Ã¤rÃ¤: </b>',
    'Description_Msg' => '<b>Kuvaus: </b>',
    'Date_Msg' => '<b>PÃ¤ivÃ¤mÃ¤Ã¤rÃ¤: </b>',
    'NewTitle_Msg' => '<b>Uusi otsikko: </b>',
    'NewHashtag_Msg' => '<b>Uusi hashtag: </b>',
    'NewDescription_Msg' => '<b>Uusi kuvaus: </b>',
    'NewDate_Msg' => '<b>Uusi pÃ¤ivÃ¤mÃ¤Ã¤rÃ¤: </b>',
    'PrizeName_Msg' => '<b>Palkinnon nimi: </b>',
    'PrizeValue_Msg' => '<b>Arvo: </b>',
    'ValueNoCurrency_Msg' => '<b>Osittainen arvo: </b>',
    'PrizeKey_Msg' => '<b>Avain: </b>',
    'PrizeType_Msg' => '<b>Tyyppi: </b>',
    'NewValue_Msg' => '<b>Uusi arvo: </b>',
    'NewValueNoCurrency_Msg' => '<b>Uusi osittainen arvo: </b>',
    'EditPrizeCurrency_Msg' => '<b>Uusi arvo: </b>',
    'TitleLenght_Msg' => 'SyÃ¶tetty otsikko on liian lyhyt. SyÃ¶tÃ¤ uusi, yli 5 merkkiÃ¤ pitkÃ¤ otsikko.',
    'ValidHashtag_Msg' => 'SyÃ¶tetty hashtag ei ole kelvollinen, syÃ¶tÃ¤ uusi hashtag.',
    'DuplicatedHashtag_Msg' => 'SyÃ¶tetty hashtag on jo kÃ¤ytÃ¶ssÃ¤, syÃ¶tÃ¤ uusi hashtag.',
    'HashtagSkipped_Msg' => '<b>Hashtag:</b> <i>Ohitettu</i>.',
    'DescriptionSkipped_Msg' => '<b>Kuvaus:</b> <i>ei kuvausta</i>.',
    'MaxparticipantsNotValid_Msg' => 'MaksimimÃ¤Ã¤rÃ¤ ei ole kelvollinen. SyÃ¶tÃ¤ uusi arvo.',
    'MaxparticipantsInfinite_Msg' => '<b>JÃ¤senten maksimimÃ¤Ã¤rÃ¤:</b> <i>ei rajattu</i>.',
    'DateNotValid_Msg' => 'SyÃ¶tetty kesto ei ole kelvollinen, syÃ¶tÃ¤ luku vÃ¤liltÃ¤ 3-40.',
    'ValueNotValid_Msg' => 'SyÃ¶tÃ¤ kelvollinen arvo.',
    'NewValueNotValid_Msg' => 'Uusi arvo ei ole kelvollinen, syÃ¶tÃ¤ uusi arvo.',
    'CancelGiveawayPrompt_Msg' => 'Haluatko varmasti peruuttaa tÃ¤mÃ¤n arvonnan valmistelun?
TÃ¤tÃ¤ ei voida perua ja kaikki syÃ¶tetyt tiedot menetetÃ¤Ã¤n.',
    'ShowHashtagMissing_Msg' => 'Sinun pitÃ¤isi syÃ¶ttÃ¤Ã¤ arvonnan hashtag:',
    'ClosedGiveawayWarn_Msg' => '<b>Pyydetty arvonta pon sulkeutunut.</b>',
    'NoGiveawayWarn_Msg' => '<b>Arvontaa ei lÃ¶ydy</b>',
    'MaxParticipants_Msg' => 'IkÃ¤vÃ¤ kyllÃ¤ arvonnassa on jo maksimimÃ¤Ã¤rÃ¤ jÃ¤seniÃ¤.',
    'JoinedSuccess_Msg' => 'Liityit arvontaan!',
    'CancelSuccess_Msg' => 'Poistit arvonnan  Â¯\_(ãƒ„)_/Â¯',
    'MissingHashtagWarn_Msg' => 'Sinun pitÃ¤isi syÃ¶ttÃ¤Ã¤ hashtag:',
    'StatsEmpty_Msg' => 'Et ole liittynyt arvontoihin',
    'Value_Msg' => 'Arvo: ',
    'Owned_Msg' => '<code>Omistettu</code>',
    'Joined_Msg' => '<code>Liitytty</code>',
    'Closed_Msg' => '<code>Suljettu</code>',
    'LastDay_Msg' => '<code>Viimeinen pÃ¤ivÃ¤</code>',
    'UserError_Msg' => '<b>Arvontaa tai kÃ¤yttÃ¤jÃ¤Ã¤, jota etsit, ei ole olemassa.</b>',
    'AlreadyIn_Msg' => '<b>Liityit jo tÃ¤hÃ¤n arvontaan.</b>',
    'ReferralLink_Msg' => 'TÃ¤mÃ¤ on viittauslinkkisi, kopioi se ja jaa kavereillesi:',
    'AfterCreation_Msg' => 'Arvonta luotu onnistuneesti!',
    'Hash_Msg' => '<b>Hashtag: </b>',
    'Type_Msg' => '<b>Tyyppi: </b>',
    'MPValue_Msg' => '<b>Osallistujia ENINTÃ„Ã„N: </b>',
    'EndDate_Msg' => '<b>LoppupÃ¤ivÃ¤mÃ¤Ã¤rÃ¤: </b>',
    'Desc_Msg' => '<b>Kuvaus: </b>',
    'GiveawayPrizes_Msg' => '<b>Palkintoja: </b>',
    'Undefined_Msg' => '<i>Ei mÃ¤Ã¤ritelty</i>',
    'TotalValue_Msg' => '<b>Arvo: </b>',
    'JoinLabel_Msg' => 'Liity ',
    'Unlimited_Msg' => '<i>Rajoittamaton</i>',
    'Inception_Msg' => '<b>Loit tÃ¤mÃ¤n arvonnan. Et voi liittyÃ¤ siihen ;)</b>',
    'NowLabel_Msg' => ' nyt ja voita upeita palkintoja!',
    'UnavailableDesc_Msg' => 'Kuvausta ei lÃ¶ydetty',
    'Days_Msg' => 'pÃ¤ivÃ¤Ã¤',
    'Menu_Button' => 'ðŸ“œ Valikko',
    'Register_Button' => 'ðŸ– Luo',
    'Show_Button' => 'ðŸ•¹ Selaa',
    'Language_Button' => 'ðŸŒ Kieli',
    'standard_Button' => 'âž¡ï¸ JoinIn',
    'cumulative_Button' => 'â†ªï¸ ShareIt',
    'Back_Button' => 'ðŸ”™ Takaisin',
    'Skip_Button' => 'ðŸ”œ Ohita',
    'Confirm_Button' => 'âœ”ï¸ Vahvista',
    'Infinite_Button' => 'âšªï¸ Ei rajoitusta',
    'EditTitle_Button' => 'ðŸ“ Muuta otsikkoa',
    'EditHashtag_Button' => '#âƒ£ Muuta hashtagia',
    'EditMaxparticipants_Button' => 'ðŸ”¢ Muuta osallistujia',
    'EditDescription_Button' => 'ðŸ“ Muuta kuvausta',
    'EditDate_Button' => 'ðŸ“… Muuta pÃ¤ivÃ¤mÃ¤Ã¤rÃ¤Ã¤',
    'DeleteHashtag_Button' => 'âŽ Poista hashtag',
    'DeleteDescription_Button' => 'âŽ Poista kuvaus',
    'AddHashtag_Button' => '#âƒ£ LisÃ¤Ã¤ hashtag',
    'AddDescription_Button' => 'ðŸ“ LisÃ¤Ã¤ kuvaus',
    'AddMaxparticipants_Button' => 'ðŸ”¢ LisÃ¤Ã¤ osallistujarajoitus',
    'ConfirmGiveaway_Button' => 'âœ”ï¸ Vahvista',
    'ConfirmPrizes_Button' => 'âœ”ï¸ Vahvista palkinnot',
    'AddPrize_Button' => 'âž• LisÃ¤Ã¤ palkinto',
    'CancelGiveaway_Button' => 'âœ–ï¸ Peruuta arvonta',
    'EditPrizeName_Button' => 'ðŸ“ Muuta nimeÃ¤',
    'EditPrizeType_Button' => 'ðŸŽ² Muuta tyyppiÃ¤',
    'EditPrizeValue_Button' => 'ðŸ’² Muuta arvoa',
    'EditPrizeCurrency_Button' => 'ðŸ’± Muuta valuuttaa',
    'DeletePrize_Button' => 'âŒ Poista',
    'Prizes_Button' => 'ðŸŽ Kaikki palkinnot',
    'Type1_Button' => 'ðŸŽ® Videopeliavain',
    'Type2_Button' => 'ðŸ“ƒ Kuponki',
    'Type3_Button' => 'ðŸ“„ Lahjakortti',
    'Type4_Button' => 'ðŸ”‘ Other',
    'Join_Button' => '#âƒ£ Liity',
    'Cancel_Button' => 'ðŸš« Peruuta',
    'Help_Button' => '*âƒ£ Ohje',
    'About_Button' => 'â„¹ï¸ Tietoja',
    'Source_Button' => 'ðŸ“– LÃ¤hdekoodi',
    'Updates_Button' => 'â• PÃ¤ivitykset',
    'ClosedGiveaway_Msg' => '<b>Pyydetty arvonta on sulkeutunut.</b>',
    'standard_AnswerCallback' => 'JoinIn',
    'cumulative_AnswerCallback' => 'ShareIt',
    'HashtagSkipped_AnswerCallback' => 'Hashtag ohitettu',
    'DescriptionSkippet_AnswerCallback' => 'Ei kuvausta',
    'MaxparticipantsInfinite_AnswerCallback' => 'Ei rajoitusta',
    'Language_AnswerCallback' => 'Valitse kieli',
    'â‚¬_AnswerCallback' => 'Euro',
    '$_AnswerCallback' => 'Dollari',
    'Register_InlineQuery' => 'RekisterÃ¶idy',
    'SwitchPM_InlineQuery' => 'Luo tai selaa',
    'ShareLink_Button' => 'Share',
    'ShowLink_Button' => 'Show link',
    'UndefinedHashtag_Msg' => '<i>No hashtag</i>',
    'BrowsePrize_Button' => 'Browse Prizes',
    'en' => 'Englanti',
    'it' => 'Italia',
    'es' => 'Espanja',
    'fr' => 'Ranska',
    'de' => 'Saksa',
    'pt' => 'Portugali',
    'ru' => 'VenÃ¤jÃ¤',
    'fi' => 'Suomi',
    'fa' => 'Farsi(persia)',
    'hi' => 'Hindi',
    'nl' => 'Hollanti',
    'zh' => 'Kiina',
];

 /*
$localization['de'] = [
    'Welcome_Msg' => "Welcome to GiveawayBot 🎰.
Choose a language to begin:",
    'Menu_Msg' => 'GiveawayBot let you create, join and manage giveaways on Telegram.
Select an option:',
    'Join_Msg' => 'Enter the giveaway hashtag you want join:',
    'Help_Msg' => 'These instructions will <b>guide you to use me.</b>

A giveaway is a promotion or contest in which prizes are given away.
This bot provides <b>two types</b> of giveaways:
<code>JoinIn</code>: Each member has the same chance of winning.
<code>ShareIt</code>: Each member increases chance of winning inviting other people to the giveaway.

You only have to join one of them for a chance to win great prizes: click on an invite link or press Join button and follow the instructions.
If you joined it, look the details by pressing <code>Browse</code> button on the menu. Anyway if you won you\'ll receive a notification with your prize.
If you want to create a giveaway, press <code>Create</code> button in the menu and follow the instructions; at the end you\'ll receive the link to share it. The winners will be chosen randomly and the bot will send them a notification containing the key.
Click /start to return to the menu.
If you experience problems click /start to reset the bot or contact @danyspin97.

<b>WE DO NOT PROVIDE WARRANTY FOR THE GIVEAWAYS. ONLY THE OWNER ADDS THE KEYS OF THE PRIZES AND WE DO NOT PROVIDE RELIABILITY FOR WHO USE THIS BOT.</b>
<i>Thank you for your attention and good luck.</i>
<code>WiseDragonStd</code>🐉',
    'About_Msg' => 'This bot is written in php and ruby. It has been developed by <code>WiseDragonStd</code>🐉 team and uses HadesWrapper.
The code will be released as open source in early 2017.
For updates follow @WiseDragonStd channel.',
    'Register_Msg' => 'Welcome to the giveaway setup. Select one of the following types:
<code>JoinIn</code>: Each member has the same chance of winning.
<code>ShareIt</code>: Each member increases chance of winning inviting other people to the giveaway.',
    'EnteringTitle_Msg' => 'Enter the giveaway title:',
    'EnteringHashtag_Msg' => 'Enter a hashtag for this giveaway or skip. A giveaway can be joined inserting the hashtag after pressing <code>Join</code> button.',
    'EnteringDescription_Msg' => 'Enter a description for the giveaway:',
    'EnteringMaxparticipants_Msg' => 'Enter the MAX members allowed to join or skip for no limits:',
    'EnteringDate_Msg' => 'Enter the life (in days) of your giveaway:
(Enter a number between 3-40)',
    'EnteringFirstPrize_Msg' => 'Now you\'ll start creating the prizes for the current giveaway.
I\'ll prompt you all the info about the current prize, then you'll se a summary where you can add more prizes.',
    'EnteringPrizeName_Msg' => 'Enter the prize name:',
    'EnteringPrizeValue_Msg' => 'Enter how much this prize worth in the form 29.99€. You can use your own currency, if it isn\'t allowed you will choose it from a list:',
    'EnteringPrizeType_Msg' => 'Select prize type:',
    'EnteringPrizeCurrency_Msg' => 'Select a currency:',
    'EnteringPrizeKey_Msg' => 'Enter a key for this prize. You cannot modify the key after entering it, so please pay attention.
This Key will be sent to winner at the end of the giveaway.
It is securely stored on a database.',
    'EditTitle_Msg' => 'Enter the new <b>title</b>:',
    'EditHashtag_Msg' => 'Enter the new <b>hashtag</b>:',
    'EditDescription_Msg' => 'Enter the new <b>description</b>:',
    'EditDate_Msg' => 'Enter the new duration of the giveaway:
(Enter a number between 3-40)',
    'EditPrizeName_Msg' => 'Enter a new prize name:',
    'EditPrizeType_Msg' => 'Enter a new prize type:',
    'Title_Msg' => '<b>Title: </b>',
    'Hashatag_Msg' => '<b>Hashtag: </b>',
    'Maxparticipants_Msg' => '<b>MAX members allowed: </b>',
    'Description_Msg' => '<b>Description: </b>',
    'Date_Msg' => '<b>Date: </b>',
    'NewTitle_Msg' => '<b>New title: </b>',
    'NewHashtag_Msg' => '<b>New hashtag: </b>',
    'NewDescription_Msg' => '<b>New description: </b>',
    'NewDate_Msg' => '<b>New date: </b>',
    'PrizeName_Msg' => '<b>Prize name: </b>',
    'PrizeValue_Msg' => '<b>Value: </b>',
    'ValueNoCurrency_Msg' => '<b>Incomplete value: </b>',
    'PrizeKey_Msg' => '<b>Key: </b>',
    'PrizeType_Msg' => '<b>Type: </b>',
    'NewValue_Msg' => '<b>New value: </b>',
    'NewValueNoCurrency_Msg' => '<b>New incomplete value: </b>',
    'EditPrizeCurrency_Msg' => '<b>New value: </b>',
    'TitleLenght_Msg' => 'The title inserted is too short. Please insert a new one longer than 5 characters.',
    'ValidHashtag_Msg' => 'The hashtag inserted is not valid, please re-insert it.',
    'DuplicatedHashtag_Msg' => 'The hashtag entered is already used, please enter a new one.',
    'HashtagSkipped_Msg' => '<b>Hashtag:</b> <i>Skipped</i>.',
    'DescriptionSkipped_Msg' => '<b>Description:</b> <i>no description</i>.',
    'MaxparticipantsNotValid_Msg' => 'The MAX members allowed is not valid. Please insert a new one.',
    'MaxparticipantsInfinite_Msg' => '<b>Max members:</b> <i>no limit</i>.',
    'DateNotValid_Msg' => 'The date inserted is not valid, please insert a number between 3-40.',
    'ValueNotValid_Msg' => 'Please insert a valid value.',
    'NewValueNotValid_Msg' => 'The new value is not valid, please insert a new one.',
    'CancelGiveawayPrompt_Msg' => 'Are you really sure you want to cancel the setup of this giveaway?
It cannot be undone and all data inserted will be lost.',
    'ShowHashtagMissing_Msg' => 'You should insert the giveaway hashtag:',
    'ClosedGiveawayWarn_Msg' => '<b>The requested giveaway is closed.</b>',
    'NoGiveawayWarn_Msg' => '<b>Giveaway not found</b>',
    'MaxParticipants_Msg' => 'Sorry but the giveaway has reached the MAX member allowed.',
    'JoinedSuccess_Msg' => 'You joined this giveaway!',
    'CancelSuccess_Msg' => 'You deleted the giveaway  ¯\_(ツ)_/¯',
    'MissingHashtagWarn_Msg' => 'You should insert an hashtag:',
    'StatsEmpty_Msg' => 'Sorry, you didn\'t join giveaways',
    'Value_Msg' => 'For a value of ',
    'Owned_Msg' => '<code>Owned</code>',
    'Joined_Msg' => '<code>Joined</code>',
    'Closed_Msg' => '<code>Closed</code>',
    'LastDay_Msg' => '<code>Last day</code>',
    'UserError_Msg' => '<b>The giveaway or the user you\'re searching for doesn\'t exist.</b>',
    'AlreadyIn_Msg' => '<b>You already joined the giveaway.</b>',
    'ReferralLink_Msg' => 'This is your referral link, copy it and share with your friends:',
    'AfterCreation_Msg' => 'Giveaway successfully created!',
    'Hash_Msg' => '<b>Hashtag: </b>',
    'Type_Msg' => '<b>Type: </b>',
    'MPValue_Msg' => '<b>MAX members allowed: </b>',
    'EndDate_Msg' => '<b>End date: </b>',
    'Desc_Msg' => '<b>Description: </b>',
    'GiveawayPrizes_Msg' => '<b>Number of prizes: </b>',
    'Undefined_Msg' => '<i>Not defined</i>',
    'TotalValue_Msg' => '<b>For a value of: </b>',
    'JoinLabel_Msg' => 'Join ',
    'Unlimited_Msg' => '<i>Unlimited</i>',
    'Inception_Msg' => '<b>You created this giveaway. You can\'t join it ;)</b>',
    'NowLabel_Msg' => ' now and win wonderful prizes!',
    'UnavailableDesc_Msg' => 'No description found',
    'Days_Msg' => 'days',
    'Menu_Button' => '📜 Menu',
    'Register_Button' => '🖍 Create',
    'Show_Button' => '🕹 Browse',
    'Language_Button' => '🌐 Language',
    'standard_Button' => '➡️ JoinIn',
    'cumulative_Button' => '↪️ ShareIt',
    'Back_Button' => '🔙 Back',
    'Skip_Button' => '🔜 Skip',
    'Confirm_Button' => '✔️ Confirm',
    'Infinite_Button' => '⚪️ No limit',
    'EditTitle_Button' => '📝 Edit title',
    'EditHashtag_Button' => '#⃣ Edit hashtag',
    'EditMaxparticipants_Button' => '🔢 Edit members',
    'EditDescription_Button' => '📝 Edit description',
    'EditDate_Button' => '📅 Edit date',
    'DeleteHashtag_Button' => '❎ Delete hashtag',
    'DeleteDescription_Button' => '❎ Delete description',
    'AddHashtag_Button' => '#⃣ Add hashtag',
    'AddDescription_Button' => '📝 Add description',
    'AddMaxparticipants_Button' => '🔢 Add members limit',
    'ConfirmGiveaway_Button' => '✔️ Confirm',
    'ConfirmPrizes_Button' => '✔️ Confirm prizes',
    'AddPrize_Button' => '➕ Add prize',
    'CancelGiveaway_Button' => '✖️ Cancel giveaway',
    'EditPrizeName_Button' => '📝 Edit name',
    'EditPrizeType_Button' => '🎲 Edit type',
    'EditPrizeValue_Button' => '💲 Edit value',
    'EditPrizeCurrency_Button' => '💱 Edit currency',
    'DeletePrize_Button' => '❌ Delete',
    'Prizes_Button' => '🎁 All prizes',
    'Type1_Button' => '🎮 Videogame key',
    'Type2_Button' => '📃 Coupon',
    'Type3_Button' => '📄 Gift Card',
    'Type4_Button' => '🔑 Other',
    'Join_Button' => '#⃣ Join',
    'Cancel_Button' => '🚫 Cancel',
    'Help_Button' => '*⃣ Help',
    'About_Button' => 'ℹ️ About',
    'Source_Button' => '📖 Source',
    'Updates_Button' => '❕ Updates',
    'ClosedGiveaway_Msg' => '<b>The requested giveaway is closed.</b>',
    'standard_AnswerCallback' => 'JoinIn',
    'cumulative_AnswerCallback' => 'ShareIt',
    'HashtagSkipped_AnswerCallback' => 'Hashtag skipped',
    'DescriptionSkippet_AnswerCallback' => 'No description',
    'MaxparticipantsInfinite_AnswerCallback' => 'No limit',
    'Language_AnswerCallback' => 'Choose language',
    '€_AnswerCallback' => 'Euro',
    '$_AnswerCallback' => 'Dollar',
    'Register_InlineQuery' => 'Register',
    'SwitchPM_InlineQuery' => 'Create or browse',
    'en' => 'English',
    'it' => 'Italian',
    'es' => 'Spanish',
    'fr' => 'French',
    'de' => 'German',
    'pt' => 'Portugues',
    'ru' => 'Russian',
    'fi' => 'Finnish',
    'fa' => 'Farsi(Persian)',
    'hi' => 'Hindi',
    'nl' => 'Dutch',
    'zh' => 'Chinese',
];

$localization['zh'] = [
    'Welcome_Msg' => "Welcome to GiveawayBot 🎰.
Choose a language to begin:",
    'Menu_Msg' => 'GiveawayBot let you create, join and manage giveaways on Telegram.
Select an option:',
    'Join_Msg' => 'Enter the giveaway hashtag you want join:',
    'Help_Msg' => 'These instructions will <b>guide you to use me.</b>

A giveaway is a promotion or contest in which prizes are given away.
This bot provides <b>two types</b> of giveaways:
<code>JoinIn</code>: Each member has the same chance of winning.
<code>ShareIt</code>: Each member increases chance of winning inviting other people to the giveaway.

You only have to join one of them for a chance to win great prizes: click on an invite link or press Join button and follow the instructions.
If you joined it, look the details by pressing <code>Browse</code> button on the menu. Anyway if you won you\'ll receive a notification with your prize.
If you want to create a giveaway, press <code>Create</code> button in the menu and follow the instructions; at the end you\'ll receive the link to share it. The winners will be chosen randomly and the bot will send them a notification containing the key.
Click /start to return to the menu.
If you experience problems click /start to reset the bot or contact @danyspin97.

<b>WE DO NOT PROVIDE WARRANTY FOR THE GIVEAWAYS. ONLY THE OWNER ADDS THE KEYS OF THE PRIZES AND WE DO NOT PROVIDE RELIABILITY FOR WHO USE THIS BOT.</b>
<i>Thank you for your attention and good luck.</i>
<code>WiseDragonStd</code>🐉',
    'About_Msg' => 'This bot is written in php and ruby. It has been developed by <code>WiseDragonStd</code>🐉 team and uses HadesWrapper.
The code will be released as open source in early 2017.
For updates follow @WiseDragonStd channel.',
    'Register_Msg' => 'Welcome to the giveaway setup. Select one of the following types:
<code>JoinIn</code>: Each member has the same chance of winning.
<code>ShareIt</code>: Each member increases chance of winning inviting other people to the giveaway.',
    'EnteringTitle_Msg' => 'Enter the giveaway title:',
    'EnteringHashtag_Msg' => 'Enter a hashtag for this giveaway or skip. A giveaway can be joined inserting the hashtag after pressing <code>Join</code> button.',
    'EnteringDescription_Msg' => 'Enter a description for the giveaway:',
    'EnteringMaxparticipants_Msg' => 'Enter the MAX members allowed to join or skip for no limits:',
    'EnteringDate_Msg' => 'Enter the life (in days) of your giveaway:
(Enter a number between 3-40)',
    'EnteringFirstPrize_Msg' => 'Now you\'ll start creating the prizes for the current giveaway.
I\'ll prompt you all the info about the current prize, then you'll se a summary where you can add more prizes.',
    'EnteringPrizeName_Msg' => 'Enter the prize name:',
    'EnteringPrizeValue_Msg' => 'Enter how much this prize worth in the form 29.99€. You can use your own currency, if it isn\'t allowed you will choose it from a list:',
    'EnteringPrizeType_Msg' => 'Select prize type:',
    'EnteringPrizeCurrency_Msg' => 'Select a currency:',
    'EnteringPrizeKey_Msg' => 'Enter a key for this prize. You cannot modify the key after entering it, so please pay attention.
This Key will be sent to winner at the end of the giveaway.
It is securely stored on a database.',
    'EditTitle_Msg' => 'Enter the new <b>title</b>:',
    'EditHashtag_Msg' => 'Enter the new <b>hashtag</b>:',
    'EditDescription_Msg' => 'Enter the new <b>description</b>:',
    'EditDate_Msg' => 'Enter the new duration of the giveaway:
(Enter a number between 3-40)',
    'EditPrizeName_Msg' => 'Enter a new prize name:',
    'EditPrizeType_Msg' => 'Enter a new prize type:',
    'Title_Msg' => '<b>Title: </b>',
    'Hashatag_Msg' => '<b>Hashtag: </b>',
    'Maxparticipants_Msg' => '<b>MAX members allowed: </b>',
    'Description_Msg' => '<b>Description: </b>',
    'Date_Msg' => '<b>Date: </b>',
    'NewTitle_Msg' => '<b>New title: </b>',
    'NewHashtag_Msg' => '<b>New hashtag: </b>',
    'NewDescription_Msg' => '<b>New description: </b>',
    'NewDate_Msg' => '<b>New date: </b>',
    'PrizeName_Msg' => '<b>Prize name: </b>',
    'PrizeValue_Msg' => '<b>Value: </b>',
    'ValueNoCurrency_Msg' => '<b>Incomplete value: </b>',
    'PrizeKey_Msg' => '<b>Key: </b>',
    'PrizeType_Msg' => '<b>Type: </b>',
    'NewValue_Msg' => '<b>New value: </b>',
    'NewValueNoCurrency_Msg' => '<b>New incomplete value: </b>',
    'EditPrizeCurrency_Msg' => '<b>New value: </b>',
    'TitleLenght_Msg' => 'The title inserted is too short. Please insert a new one longer than 5 characters.',
    'ValidHashtag_Msg' => 'The hashtag inserted is not valid, please re-insert it.',
    'DuplicatedHashtag_Msg' => 'The hashtag entered is already used, please enter a new one.',
    'HashtagSkipped_Msg' => '<b>Hashtag:</b> <i>Skipped</i>.',
    'DescriptionSkipped_Msg' => '<b>Description:</b> <i>no description</i>.',
    'MaxparticipantsNotValid_Msg' => 'The MAX members allowed is not valid. Please insert a new one.',
    'MaxparticipantsInfinite_Msg' => '<b>Max members:</b> <i>no limit</i>.',
    'DateNotValid_Msg' => 'The date inserted is not valid, please insert a number between 3-40.',
    'ValueNotValid_Msg' => 'Please insert a valid value.',
    'NewValueNotValid_Msg' => 'The new value is not valid, please insert a new one.',
    'CancelGiveawayPrompt_Msg' => 'Are you really sure you want to cancel the setup of this giveaway?
It cannot be undone and all data inserted will be lost.',
    'ShowHashtagMissing_Msg' => 'You should insert the giveaway hashtag:',
    'ClosedGiveawayWarn_Msg' => '<b>The requested giveaway is closed.</b>',
    'NoGiveawayWarn_Msg' => '<b>Giveaway not found</b>',
    'MaxParticipants_Msg' => 'Sorry but the giveaway has reached the MAX member allowed.',
    'JoinedSuccess_Msg' => 'You joined this giveaway!',
    'CancelSuccess_Msg' => 'You deleted the giveaway  ¯\_(ツ)_/¯',
    'MissingHashtagWarn_Msg' => 'You should insert an hashtag:',
    'StatsEmpty_Msg' => 'Sorry, you didn\'t join giveaways',
    'Value_Msg' => 'For a value of ',
    'Owned_Msg' => '<code>Owned</code>',
    'Joined_Msg' => '<code>Joined</code>',
    'Closed_Msg' => '<code>Closed</code>',
    'LastDay_Msg' => '<code>Last day</code>',
    'UserError_Msg' => '<b>The giveaway or the user you\'re searching for doesn\'t exist.</b>',
    'AlreadyIn_Msg' => '<b>You already joined the giveaway.</b>',
    'ReferralLink_Msg' => 'This is your referral link, copy it and share with your friends:',
    'AfterCreation_Msg' => 'Giveaway successfully created!',
    'Hash_Msg' => '<b>Hashtag: </b>',
    'Type_Msg' => '<b>Type: </b>',
    'MPValue_Msg' => '<b>MAX members allowed: </b>',
    'EndDate_Msg' => '<b>End date: </b>',
    'Desc_Msg' => '<b>Description: </b>',
    'GiveawayPrizes_Msg' => '<b>Number of prizes: </b>',
    'Undefined_Msg' => '<i>Not defined</i>',
    'TotalValue_Msg' => '<b>For a value of: </b>',
    'JoinLabel_Msg' => 'Join ',
    'Unlimited_Msg' => '<i>Unlimited</i>',
    'Inception_Msg' => '<b>You created this giveaway. You can\'t join it ;)</b>',
    'NowLabel_Msg' => ' now and win wonderful prizes!',
    'UnavailableDesc_Msg' => 'No description found',
    'Days_Msg' => 'days',
    'Menu_Button' => '📜 Menu',
    'Register_Button' => '🖍 Create',
    'Show_Button' => '🕹 Browse',
    'Language_Button' => '🌐 Language',
    'standard_Button' => '➡️ JoinIn',
    'cumulative_Button' => '↪️ ShareIt',
    'Back_Button' => '🔙 Back',
    'Skip_Button' => '🔜 Skip',
    'Confirm_Button' => '✔️ Confirm',
    'Infinite_Button' => '⚪️ No limit',
    'EditTitle_Button' => '📝 Edit title',
    'EditHashtag_Button' => '#⃣ Edit hashtag',
    'EditMaxparticipants_Button' => '🔢 Edit members',
    'EditDescription_Button' => '📝 Edit description',
    'EditDate_Button' => '📅 Edit date',
    'DeleteHashtag_Button' => '❎ Delete hashtag',
    'DeleteDescription_Button' => '❎ Delete description',
    'AddHashtag_Button' => '#⃣ Add hashtag',
    'AddDescription_Button' => '📝 Add description',
    'AddMaxparticipants_Button' => '🔢 Add members limit',
    'ConfirmGiveaway_Button' => '✔️ Confirm',
    'ConfirmPrizes_Button' => '✔️ Confirm prizes',
    'AddPrize_Button' => '➕ Add prize',
    'CancelGiveaway_Button' => '✖️ Cancel giveaway',
    'EditPrizeName_Button' => '📝 Edit name',
    'EditPrizeType_Button' => '🎲 Edit type',
    'EditPrizeValue_Button' => '💲 Edit value',
    'EditPrizeCurrency_Button' => '💱 Edit currency',
    'DeletePrize_Button' => '❌ Delete',
    'Prizes_Button' => '🎁 All prizes',
    'Type1_Button' => '🎮 Videogame key',
    'Type2_Button' => '📃 Coupon',
    'Type3_Button' => '📄 Gift Card',
    'Type4_Button' => '🔑 Other',
    'Join_Button' => '#⃣ Join',
    'Cancel_Button' => '🚫 Cancel',
    'Help_Button' => '*⃣ Help',
    'About_Button' => 'ℹ️ About',
    'Source_Button' => '📖 Source',
    'Updates_Button' => '❕ Updates',
    'ClosedGiveaway_Msg' => '<b>The requested giveaway is closed.</b>',
    'standard_AnswerCallback' => 'JoinIn',
    'cumulative_AnswerCallback' => 'ShareIt',
    'HashtagSkipped_AnswerCallback' => 'Hashtag skipped',
    'DescriptionSkippet_AnswerCallback' => 'No description',
    'MaxparticipantsInfinite_AnswerCallback' => 'No limit',
    'Language_AnswerCallback' => 'Choose language',
    '€_AnswerCallback' => 'Euro',
    '$_AnswerCallback' => 'Dollar',
    'Register_InlineQuery' => 'Register',
    'SwitchPM_InlineQuery' => 'Create or browse',
    'en' => 'English',
    'it' => 'Italian',
    'es' => 'Spanish',
    'fr' => 'French',
    'de' => 'German',
    'pt' => 'Portugues',
    'ru' => 'Russian',
    'fi' => 'Finnish',
    'fa' => 'Farsi(Persian)',
    'hi' => 'Hindi',
    'nl' => 'Dutch',
    'zh' => 'Chinese',
];

$localization['nl'] = [
    'Welcome_Msg' => "Welcome to GiveawayBot 🎰.
Choose a language to begin:",
    'Menu_Msg' => 'GiveawayBot let you create, join and manage giveaways on Telegram.
Select an option:',
    'Join_Msg' => 'Enter the giveaway hashtag you want join:',
    'Help_Msg' => 'These instructions will <b>guide you to use me.</b>

A giveaway is a promotion or contest in which prizes are given away.
This bot provides <b>two types</b> of giveaways:
<code>JoinIn</code>: Each member has the same chance of winning.
<code>ShareIt</code>: Each member increases chance of winning inviting other people to the giveaway.

You only have to join one of them for a chance to win great prizes: click on an invite link or press Join button and follow the instructions.
If you joined it, look the details by pressing <code>Browse</code> button on the menu. Anyway if you won you\'ll receive a notification with your prize.
If you want to create a giveaway, press <code>Create</code> button in the menu and follow the instructions; at the end you\'ll receive the link to share it. The winners will be chosen randomly and the bot will send them a notification containing the key.
Click /start to return to the menu.
If you experience problems click /start to reset the bot or contact @danyspin97.

<b>WE DO NOT PROVIDE WARRANTY FOR THE GIVEAWAYS. ONLY THE OWNER ADDS THE KEYS OF THE PRIZES AND WE DO NOT PROVIDE RELIABILITY FOR WHO USE THIS BOT.</b>
<i>Thank you for your attention and good luck.</i>
<code>WiseDragonStd</code>🐉',
    'About_Msg' => 'This bot is written in php and ruby. It has been developed by <code>WiseDragonStd</code>🐉 team and uses HadesWrapper.
The code will be released as open source in early 2017.
For updates follow @WiseDragonStd channel.',
    'Register_Msg' => 'Welcome to the giveaway setup. Select one of the following types:
<code>JoinIn</code>: Each member has the same chance of winning.
<code>ShareIt</code>: Each member increases chance of winning inviting other people to the giveaway.',
    'EnteringTitle_Msg' => 'Enter the giveaway title:',
    'EnteringHashtag_Msg' => 'Enter a hashtag for this giveaway or skip. A giveaway can be joined inserting the hashtag after pressing <code>Join</code> button.',
    'EnteringDescription_Msg' => 'Enter a description for the giveaway:',
    'EnteringMaxparticipants_Msg' => 'Enter the MAX members allowed to join or skip for no limits:',
    'EnteringDate_Msg' => 'Enter the life (in days) of your giveaway:
(Enter a number between 3-40)',
    'EnteringFirstPrize_Msg' => 'Now you\'ll start creating the prizes for the current giveaway.
I\'ll prompt you all the info about the current prize, then you'll se a summary where you can add more prizes.',
    'EnteringPrizeName_Msg' => 'Enter the prize name:',
    'EnteringPrizeValue_Msg' => 'Enter how much this prize worth in the form 29.99€. You can use your own currency, if it isn\'t allowed you will choose it from a list:',
    'EnteringPrizeType_Msg' => 'Select prize type:',
    'EnteringPrizeCurrency_Msg' => 'Select a currency:',
    'EnteringPrizeKey_Msg' => 'Enter a key for this prize. You cannot modify the key after entering it, so please pay attention.
This Key will be sent to winner at the end of the giveaway.
It is securely stored on a database.',
    'EditTitle_Msg' => 'Enter the new <b>title</b>:',
    'EditHashtag_Msg' => 'Enter the new <b>hashtag</b>:',
    'EditDescription_Msg' => 'Enter the new <b>description</b>:',
    'EditDate_Msg' => 'Enter the new duration of the giveaway:
(Enter a number between 3-40)',
    'EditPrizeName_Msg' => 'Enter a new prize name:',
    'EditPrizeType_Msg' => 'Enter a new prize type:',
    'Title_Msg' => '<b>Title: </b>',
    'Hashatag_Msg' => '<b>Hashtag: </b>',
    'Maxparticipants_Msg' => '<b>MAX members allowed: </b>',
    'Description_Msg' => '<b>Description: </b>',
    'Date_Msg' => '<b>Date: </b>',
    'NewTitle_Msg' => '<b>New title: </b>',
    'NewHashtag_Msg' => '<b>New hashtag: </b>',
    'NewDescription_Msg' => '<b>New description: </b>',
    'NewDate_Msg' => '<b>New date: </b>',
    'PrizeName_Msg' => '<b>Prize name: </b>',
    'PrizeValue_Msg' => '<b>Value: </b>',
    'ValueNoCurrency_Msg' => '<b>Incomplete value: </b>',
    'PrizeKey_Msg' => '<b>Key: </b>',
    'PrizeType_Msg' => '<b>Type: </b>',
    'NewValue_Msg' => '<b>New value: </b>',
    'NewValueNoCurrency_Msg' => '<b>New incomplete value: </b>',
    'EditPrizeCurrency_Msg' => '<b>New value: </b>',
    'TitleLenght_Msg' => 'The title inserted is too short. Please insert a new one longer than 5 characters.',
    'ValidHashtag_Msg' => 'The hashtag inserted is not valid, please re-insert it.',
    'DuplicatedHashtag_Msg' => 'The hashtag entered is already used, please enter a new one.',
    'HashtagSkipped_Msg' => '<b>Hashtag:</b> <i>Skipped</i>.',
    'DescriptionSkipped_Msg' => '<b>Description:</b> <i>no description</i>.',
    'MaxparticipantsNotValid_Msg' => 'The MAX members allowed is not valid. Please insert a new one.',
    'MaxparticipantsInfinite_Msg' => '<b>Max members:</b> <i>no limit</i>.',
    'DateNotValid_Msg' => 'The date inserted is not valid, please insert a number between 3-40.',
    'ValueNotValid_Msg' => 'Please insert a valid value.',
    'NewValueNotValid_Msg' => 'The new value is not valid, please insert a new one.',
    'CancelGiveawayPrompt_Msg' => 'Are you really sure you want to cancel the setup of this giveaway?
It cannot be undone and all data inserted will be lost.',
    'ShowHashtagMissing_Msg' => 'You should insert the giveaway hashtag:',
    'ClosedGiveawayWarn_Msg' => '<b>The requested giveaway is closed.</b>',
    'NoGiveawayWarn_Msg' => '<b>Giveaway not found</b>',
    'MaxParticipants_Msg' => 'Sorry but the giveaway has reached the MAX member allowed.',
    'JoinedSuccess_Msg' => 'You joined this giveaway!',
    'CancelSuccess_Msg' => 'You deleted the giveaway  ¯\_(ツ)_/¯',
    'MissingHashtagWarn_Msg' => 'You should insert an hashtag:',
    'StatsEmpty_Msg' => 'Sorry, you didn\'t join giveaways',
    'Value_Msg' => 'For a value of ',
    'Owned_Msg' => '<code>Owned</code>',
    'Joined_Msg' => '<code>Joined</code>',
    'Closed_Msg' => '<code>Closed</code>',
    'LastDay_Msg' => '<code>Last day</code>',
    'UserError_Msg' => '<b>The giveaway or the user you\'re searching for doesn\'t exist.</b>',
    'AlreadyIn_Msg' => '<b>You already joined the giveaway.</b>',
    'ReferralLink_Msg' => 'This is your referral link, copy it and share with your friends:',
    'AfterCreation_Msg' => 'Giveaway successfully created!',
    'Hash_Msg' => '<b>Hashtag: </b>',
    'Type_Msg' => '<b>Type: </b>',
    'MPValue_Msg' => '<b>MAX members allowed: </b>',
    'EndDate_Msg' => '<b>End date: </b>',
    'Desc_Msg' => '<b>Description: </b>',
    'GiveawayPrizes_Msg' => '<b>Number of prizes: </b>',
    'Undefined_Msg' => '<i>Not defined</i>',
    'TotalValue_Msg' => '<b>For a value of: </b>',
    'JoinLabel_Msg' => 'Join ',
    'Unlimited_Msg' => '<i>Unlimited</i>',
    'Inception_Msg' => '<b>You created this giveaway. You can\'t join it ;)</b>',
    'NowLabel_Msg' => ' now and win wonderful prizes!',
    'UnavailableDesc_Msg' => 'No description found',
    'Days_Msg' => 'days',
    'Menu_Button' => '📜 Menu',
    'Register_Button' => '🖍 Create',
    'Show_Button' => '🕹 Browse',
    'Language_Button' => '🌐 Language',
    'standard_Button' => '➡️ JoinIn',
    'cumulative_Button' => '↪️ ShareIt',
    'Back_Button' => '🔙 Back',
    'Skip_Button' => '🔜 Skip',
    'Confirm_Button' => '✔️ Confirm',
    'Infinite_Button' => '⚪️ No limit',
    'EditTitle_Button' => '📝 Edit title',
    'EditHashtag_Button' => '#⃣ Edit hashtag',
    'EditMaxparticipants_Button' => '🔢 Edit members',
    'EditDescription_Button' => '📝 Edit description',
    'EditDate_Button' => '📅 Edit date',
    'DeleteHashtag_Button' => '❎ Delete hashtag',
    'DeleteDescription_Button' => '❎ Delete description',
    'AddHashtag_Button' => '#⃣ Add hashtag',
    'AddDescription_Button' => '📝 Add description',
    'AddMaxparticipants_Button' => '🔢 Add members limit',
    'ConfirmGiveaway_Button' => '✔️ Confirm',
    'ConfirmPrizes_Button' => '✔️ Confirm prizes',
    'AddPrize_Button' => '➕ Add prize',
    'CancelGiveaway_Button' => '✖️ Cancel giveaway',
    'EditPrizeName_Button' => '📝 Edit name',
    'EditPrizeType_Button' => '🎲 Edit type',
    'EditPrizeValue_Button' => '💲 Edit value',
    'EditPrizeCurrency_Button' => '💱 Edit currency',
    'DeletePrize_Button' => '❌ Delete',
    'Prizes_Button' => '🎁 All prizes',
    'Type1_Button' => '🎮 Videogame key',
    'Type2_Button' => '📃 Coupon',
    'Type3_Button' => '📄 Gift Card',
    'Type4_Button' => '🔑 Other',
    'Join_Button' => '#⃣ Join',
    'Cancel_Button' => '🚫 Cancel',
    'Help_Button' => '*⃣ Help',
    'About_Button' => 'ℹ️ About',
    'Source_Button' => '📖 Source',
    'Updates_Button' => '❕ Updates',
    'ClosedGiveaway_Msg' => '<b>The requested giveaway is closed.</b>',
    'standard_AnswerCallback' => 'JoinIn',
    'cumulative_AnswerCallback' => 'ShareIt',
    'HashtagSkipped_AnswerCallback' => 'Hashtag skipped',
    'DescriptionSkippet_AnswerCallback' => 'No description',
    'MaxparticipantsInfinite_AnswerCallback' => 'No limit',
    'Language_AnswerCallback' => 'Choose language',
    '€_AnswerCallback' => 'Euro',
    '$_AnswerCallback' => 'Dollar',
    'Register_InlineQuery' => 'Register',
    'SwitchPM_InlineQuery' => 'Create or browse',
    'en' => 'English',
    'it' => 'Italian',
    'es' => 'Spanish',
    'fr' => 'French',
    'de' => 'German',
    'pt' => 'Portugues',
    'ru' => 'Russian',
    'fi' => 'Finnish',
    'fa' => 'Farsi(Persian)',
    'hi' => 'Hindi',
    'nl' => 'Dutch',
    'zh' => 'Chinese',
];

 */
$localization['ru'] = [
    'Welcome_Msg' => "Добро пожаловать в GiveawayBot 🎰.
Выберите язык, чтобы начать:",
    'Menu_Msg' => 'GiveawayBot позволяет вам создавать раздачи, управлять ими присоединяться к уже существующим прямо в Телеграме.
Выберите опцию:',
    'Join_Msg' => 'Ввести хэштэг раздачи, к который вы хотите присоединиться:',
    'Help_Msg' => 'These instructions will <b>guide you to use me.</b>

Раздача (giveaway) - это промоакция или конкурс, в котором раздаются призы.
Данный бот предоставляет <b>два типа</b> раздач:
<code>JoinIn</code>: У каждого участника есть одинаковые шансы на победу.
<code>ShareIt</code>: Шансы на победу можно увеличить, приглашая других участников в раздачу.

Вам всего лишь надо присоединиться к одному из них, чтобы получить шанс на выигрыш больших призов: нажмите на ссылку-приглашение или нажмите на кнопку Join и следуйте инструкциям.
Если вы присоединились к раздаче, вы можете узнать детали, нажав на кнопку <code>Browse</code> в меню. В любом случае, если вы выиграете, вы получите оповещение с вашим призом.
Есл ивы хотите создать радачу, нажмите кнопку <code>Create</code> в меню и следуйте инструкциям; в конце у вас будет ссылка, которой вы сможете поделиться. Победители будут выбраны случайным образом, и бот пришлёт пришлёт им уведомление с кодом.
Нажмите /start чтобы вернуться в меню.
Если у вас возникнут проблемы, нажмите /start чтобы перезапустить бота, или свяжитесь с @danyspin97.

<b>МЫ НЕ ДАЁМ ГАРАНТИЙ ДЛЯ РАЗДАЧ. ИМЕННО СОЗДАТЕЛЬ РАЗДАЧИ ДОБАВЛЯЕТ КОДЫ ПРИЗОВ, И МЫ НЕ ОБЕСПЕЧИВАЕМ НАДЁЖНОСТЬ ЛЮДЕЙ, ИСПОЛЬЗУЮЩИХ ЭТОГО БОТА.</b>
<i>Спасибо за внимание и удачи!</i>
<code>WiseDragonStd</code>🐉',
    'About_Msg' => 'Этот бот написан на php и ruby. Он был создан командой <code>WiseDragonStd</code>🐉 и использует HadesWrapper.
Открытый исходный код будет опубликован в начале 2017.
Следите за обновлениями на канале @WiseDragonStd.',
    'Register_Msg' => 'Добро пожаловать в настройки раздачи. Выберите тип раздачи:
<code>JoinIn</code>: У каждого участника есть одинаковые шансы на победу.
<code>ShareIt</code>: Шансы на победу можно увеличить, приглашая других участников в раздачу.',
    'EnteringTitle_Msg' => 'Введите название раздачи:',
    'EnteringHashtag_Msg' => 'Введите хэштэг для этой раздачи или пропустите это шаг. К раздаче можно присоединиться, написав хэштэг после нажатия на кнопку <code>Join</code>.',
    'EnteringDescription_Msg' => 'Введите описание для раздачи:',
    'EnteringMaxparticipants_Msg' => 'Введите максимальное количество участников, или пропустите, чтобы не устанавливать лимит:',
    'EnteringDate_Msg' => 'Введите время жизни раздачи (в днях):
(Введите число от 3 до 40)',
    'EnteringFirstPrize_Msg' => 'Сейчас вы сможете создать призы для текущей раздачи.
I\'ll prompt you all the info about the current prize, then you\'ll see a summary where you can add more prizes.',
    'EnteringPrizeName_Msg' => 'Введите название приза:',
    'EnteringPrizeValue_Msg' => 'Введите стоимость этого приза в формате 29.99€. Вы можете использовать свою валюту, или выберите её из списка:',
    'EnteringPrizeType_Msg' => 'Выберите тип приза:',
    'EnteringPrizeCurrency_Msg' => 'Выберите валюту:',
    'EnteringPrizeKey_Msg' => 'Введите ключ для этого приза. После ввода ключа его будет невозможно изменить, поэтому будьте внимательны.
Этот ключ будет послан победителю в конце раздачи.
Он хранится в безопасности в базе данных.',
    'EditTitle_Msg' => 'Введите новое <b>название</b>:',
    'EditHashtag_Msg' => 'Введите новый <b>хэштэг</b>:',
    'EditDescription_Msg' => 'Введите новое <b>описание</b>:',
    'EditDate_Msg' => 'Введите новую продолжительность раздачи:
(Введите число от 3 до 40)',
    'EditPrizeName_Msg' => 'Введите новое название приза:',
    'EditPrizeType_Msg' => 'Введите новый тип приза:',
    'Title_Msg' => '<b>Название: </b>',
    'Hashatag_Msg' => '<b>Хэштэг: </b>',
    'Maxparticipants_Msg' => '<b>Максимальное количество участников: </b>',
    'Description_Msg' => '<b>Описание: </b>',
    'Date_Msg' => '<b>Дата: </b>',
    'NewTitle_Msg' => '<b>Новое название: </b>',
    'NewHashtag_Msg' => '<b>Новый хэштэг: </b>',
    'NewDescription_Msg' => '<b>Новое описание: </b>',
    'NewDate_Msg' => '<b>Новая дата: </b>',
    'PrizeName_Msg' => '<b>Название приза: </b>',
    'PrizeValue_Msg' => '<b>Стоимость: </b>',
    'ValueNoCurrency_Msg' => '<b>Incomplete value: </b>',
    'PrizeKey_Msg' => '<b>Ключ: </b>',
    'PrizeType_Msg' => '<b>Тип: </b>',
    'NewValue_Msg' => '<b>Новая стоимость: </b>',
    'NewValueNoCurrency_Msg' => '<b>Новая неполная стоимость: </b>',
    'EditPrizeCurrency_Msg' => '<b>Новая стоимость: </b>',
    'TitleLenght_Msg' => 'Введённое название слишком короткое. Пожалуйста, введите новое название длиннее 5 символов.',
    'ValidHashtag_Msg' => 'Введённый хэштэг недействителен, пожалуйста, введите его снова.',
    'DuplicatedHashtag_Msg' => 'Это хэштэг уже использован, пожалуйста введите новый.',
    'HashtagSkipped_Msg' => '<b>Хэштэг:</b> <i>Пропущен</i>.',
    'DescriptionSkipped_Msg' => '<b>Описание:</b> <i>нет описания</i>.',
    'MaxparticipantsNotValid_Msg' => 'Максимальное количество участников недействительно. Введите новое количество.',
    'MaxparticipantsInfinite_Msg' => '<b>Максимальное количество:</b> <i>без ограничений</i>.',
    'DateNotValid_Msg' => 'Введённая продолжительность недействительна, введите число от 3 до 40.',
    'ValueNotValid_Msg' => 'Введите корректную стоимость.',
    'NewValueNotValid_Msg' => 'Новая стоимость недействительна, введите корректное значение.',
    'CancelGiveawayPrompt_Msg' => 'Вы действительно хотите отменить настройку этой раздачи?
Это необратимо, и вся введённая информация будет потеряна.',
    'ShowHashtagMissing_Msg' => 'Вы должны ввести хэштэг раздачи:',
    'ClosedGiveawayWarn_Msg' => '<b>Запрошенная раздача закрыта.</b>',
    'NoGiveawayWarn_Msg' => '<b>Раздача не найдена</b>',
    'MaxParticipants_Msg' => 'К сожалению данная раздача достигла лимита разрешённых участников.',
    'JoinedSuccess_Msg' => 'Вы присоединились к этой раздаче!',
    'CancelSuccess_Msg' => 'Вы удалили раздачу ¯\_(ツ)_/¯',
    'MissingHashtagWarn_Msg' => 'Вы должны ввести хэштэг:',
    'StatsEmpty_Msg' => 'К сожалению, вы не присоединялись к раздачам',
    'Value_Msg' => 'Стоимостью',
    'Owned_Msg' => '<code>Owned</code>',
    'Joined_Msg' => '<code>Joined</code>',
    'Closed_Msg' => '<code>Closed</code>',
    'LastDay_Msg' => '<code>Last day</code>',
    'UserError_Msg' => '<b>Раздача пользователя, которого вы ищете, не существует.</b>',
    'AlreadyIn_Msg' => '<b>Вы уже присоединились к раздаче.</b>',
    'ReferralLink_Msg' => 'Это ваша реферральная ссылка. Скопируйте её и поделитесь ей с друзьями:',
    'AfterCreation_Msg' => 'Раздача успешно создана!',
    'Hash_Msg' => '<b>Хэштэг: </b>',
    'Type_Msg' => '<b>Тип: </b>',
    'MPValue_Msg' => '<b>Максимальное количество участников: </b>',
    'EndDate_Msg' => '<b>Дата окончания: </b>',
    'Desc_Msg' => '<b>Описание: </b>',
    'GiveawayPrizes_Msg' => '<b>Количество призов: </b>',
    'Undefined_Msg' => '<i>Не определено</i>',
    'TotalValue_Msg' => '<b>Стоимостью: </b>',
    'JoinLabel_Msg' => 'Join ',
    'Unlimited_Msg' => '<i>Неограниченное</i>',
    'Inception_Msg' => '<b>Вы создали эту раздачу, вы не можете к ней присоединиться ;)</b>',
    'NowLabel_Msg' => ' now and win wonderful prizes!',
    'UnavailableDesc_Msg' => 'Описание не найдено',
    'Days_Msg' => 'дней',
    'Menu_Button' => '📜 Меню',
    'Register_Button' => '🖍 Создать',
    'Show_Button' => '🕹 Просмотреть',
    'Language_Button' => '🌐 Language',
    'standard_Button' => '➡️ JoinIn',
    'cumulative_Button' => '↪️ ShareIt',
    'Back_Button' => '🔙 Назад',
    'Skip_Button' => '🔜 Пропустить',
    'Confirm_Button' => '✔️ Подтвердить',
    'Infinite_Button' => '⚪️ Без лимита',
    'EditTitle_Button' => '📝 Изменить название',
    'EditHashtag_Button' => '#⃣ Изменить хэштэг',
    'EditMaxparticipants_Button' => '🔢 Изменить число участников',
    'EditDescription_Button' => '📝 Изменить описание',
    'EditDate_Button' => '📅 Изменить date',
    'DeleteHashtag_Button' => '❎ Удалить хэштэг',
    'DeleteDescription_Button' => '❎ Удалить описание',
    'AddHashtag_Button' => '#⃣ Добавить хэштэг',
    'AddDescription_Button' => '📝 Добавить описание',
    'AddMaxparticipants_Button' => '🔢 Добавить лимит участников',
    'ConfirmGiveaway_Button' => '✔️ Подтвердить',
    'ConfirmPrizes_Button' => '✔️ Подтвердить призы',
    'AddPrize_Button' => '➕ Добавить приз',
    'CancelGiveaway_Button' => '✖️ Отменить раздачу',
    'EditPrizeName_Button' => '📝 Изменить название',
    'EditPrizeType_Button' => '🎲 Изменить тип',
    'EditPrizeValue_Button' => '💲 Изменить стоимость',
    'EditPrizeCurrency_Button' => '💱 Изменить валюту',
    'DeletePrize_Button' => '❌ Удалить',
    'Prizes_Button' => '🎁 Все призы',
    'Type1_Button' => '🎮 Ключ к игре',
    'Type2_Button' => '📃 Купон',
    'Type3_Button' => '📄 Подарочная карта',
    'Type4_Button' => '🔑 Другое',
    'Join_Button' => '#⃣ Присоединиться',
    'Cancel_Button' => '🚫 Отмена',
    'Help_Button' => '*⃣ Помощь',
    'About_Button' => 'ℹ️ О боте',
    'Source_Button' => '📖 Source',
    'Updates_Button' => '❕ Обновления',
    'ClosedGiveaway_Msg' => '<b>Запрашиваемая раздача закрыта.</b>',
    'standard_AnswerCallback' => 'JoinIn',
    'cumulative_AnswerCallback' => 'ShareIt',
    'HashtagSkipped_AnswerCallback' => 'Хэштэг пропущен',
    'DescriptionSkippet_AnswerCallback' => 'Нет описания',
    'MaxparticipantsInfinite_AnswerCallback' => 'Без лимита',
    'Language_AnswerCallback' => 'Choose language',
    '€_AnswerCallback' => 'Euro',
    '$_AnswerCallback' => 'Dollar',
    'Register_InlineQuery' => 'Register',
    'SwitchPM_InlineQuery' => 'Create or browse',
    'ShareLink_Button' => 'Share',
    'ShowLink_Button' => 'Show link',
    'UndefinedHashtag_Msg' => '<i>No hashtag</i>',
    'BrowsePrize_Button' => 'Browse Prizes',
    'en' => 'English',
    'it' => 'Italian',
    'es' => 'Spanish',
    'fr' => 'French',
    'de' => 'German',
    'pt' => 'Portugues',
    'ru' => 'Russian',
    'fi' => 'Finnish',
    'fa' => 'Farsi(Persian)',
    'hi' => 'Hindi',
    'nl' => 'Dutch',
    'zh' => 'Chinese',
];

$localization['br'] = [
    'Welcome_Msg' => "Bem-vindo ao GiveawayBot 🎰.
Escolha uma linguagem para iniciar:",
    'Menu_Msg' => 'GiveawayBot permite a você criar, participar e gerenciar sorteios no Telegram.
Selecionar uma opção:',
    'Join_Msg' => 'Insira a hashtag do sorteio que deseja participar:',
    'Help_Msg' => 'Essas instruções irão lhe <b>guiar para me usar.</b>

Um sorteio é uma promoção ou competição onde prêmios são dados.
Esse bot fornece <b>dois tipos</b> de sorteios:
<code>JoinIn</code>: Cada membro tem a mesma chance de ganhar.
<code>ShareIt</code>: Cada membro aumenta as chances de ganhar convidando outras pessoas ao sorteio.

Você só precisa participar de um sorteio para ter sua chance de ganhar grandes prêmios: Clique em um link de convite ou aperte o botão Participar e siga as intruções.
Se você estiver participando de um sorteio, é possível visualizar os detalhes apertando o botão <code>Navegar</code> no menu. De qualquer maneira será enviada uma notificação com seu prêmio se você ganhar o sorteio.
Se você desejar criar um sorteio, aperte o botão <code>Criar</code> no menu e siga as instruções; No fim você irá receber um link de compartilhamento. Os vencedores serão escolhidos aleatoriamente e o bot irá enviar uma notificação contendo a chave.
Clique /start para retornar ao menu.
Se você tiver problemas, clique /start para reiniciar o bot ou contate @danyspin97.

<b>NÓS NÃO PROVEMOS GARANTIA PARA OS SORTEIOS. SOMENTE O DONO ADICIONA AS CHAVES DO PRODUTO E NÓS NÃO PROVEMOS CONFIABILIDADE PARA AQUELES QUE USAREM O BOT.</b>
<i>Agradecemos pela sua atenção e desejamos boa sorte.</i>
<code>WiseDragonStd</code>🐉',
    'About_Msg' => 'Este bot foi escrito em php e ruby. Ele foi desenvolvido pela equipe <code>WiseDragonStd</code>🐉 e usa HadesWrapper.
O código será lançado como open source no começo de 2017.
Para atualização siga o canal @WiseDragonStd.',
    'Register_Msg' => 'Bem vindo a configuração do sorteio. Selecione um dos seguintes tipos:
<code>JoinIn</code>: Cada membro tem a mesma chance de ganhar.
<code>ShareIt</code>: Cada membro aumenta a chance de ganhar convidando outras pessoas ao sorteio.',
    'EnteringTitle_Msg' => 'Insira o título do sorteio:',
    'EnteringHashtag_Msg' => 'Insira uma hashtag para esse sorteio ou pule. As pessoas podem se inscrever em seu sorteio inserindo a hashtag após pressionar o botão <code>Participar</code>.',
    'EnteringDescription_Msg' => 'Insira a descrição para o sorteio:',
    'EnteringMaxparticipants_Msg' => 'Insira o número máximo de membros permitidos para participar, ou pule para não ter limites:',
    'EnteringDate_Msg' => 'Insira a duração (em dias) de seu sorteio:
(Insira um número entre 3-40)',
    'EnteringFirstPrize_Msg' => 'Agora você irá começar a criar os prêmios para o sorteio atual.
Eu irei te pedir todas as informações para o prêmio atual, então você verá um sumário onde você pode adicionar mais prêmios.',
    'EnteringPrizeName_Msg' => 'Insira o nome do prêmio:',
    'EnteringPrizeValue_Msg' => 'Insira quanto este prêmio vale no formato 29.99€. Você pode usar sua própria moeda, se ela não for aceita, você precisará escolher da lista abaixo:',
    'EnteringPrizeType_Msg' => 'Selecione o tipo do prêmio:',
    'EnteringPrizeCurrency_Msg' => 'Selecione uma moeda:',
    'EnteringPrizeKey_Msg' => 'Insira uma chave para este prêmio. Você não pode modificar a chave depois de inseri-la, então preste atenção.
Esta chave será enviada ao vencedor no fim do sorteio.
Ele será guardado seguramente em nosso banco de dados.',
    'EditTitle_Msg' => 'Insira um novo <b>título</b>:',
    'EditHashtag_Msg' => 'Insira uma nova <b>hashtag</b>:',
    'EditDescription_Msg' => 'Insira uma nova <b>descrição</b>:',
    'EditDate_Msg' => 'Insira a nova duração do sorteio:
(Insira um número entre 3-40)',
    'EditPrizeName_Msg' => 'Insira o novo nome do prêmio:',
    'EditPrizeType_Msg' => 'Insira o novo tipo do prêmio:',
    'Title_Msg' => '<b>Título: </b>',
    'Hashatag_Msg' => '<b>Hashtag: </b>',
    'Maxparticipants_Msg' => '<b>Número máximo de usuários permitidos: </b>',
    'Description_Msg' => '<b>Descrição: </b>',
    'Date_Msg' => '<b>Data: </b>',
    'NewTitle_Msg' => '<b>Novo título: </b>',
    'NewHashtag_Msg' => '<b>Nova hashtag: </b>',
    'NewDescription_Msg' => '<b>Nova descrição: </b>',
    'NewDate_Msg' => '<b>Nova data: </b>',
    'PrizeName_Msg' => '<b>Nome do Prêmio: </b>',
    'PrizeValue_Msg' => '<b>Valor: </b>',
    'ValueNoCurrency_Msg' => '<b>Valor incompleto: </b>',
    'PrizeKey_Msg' => '<b>Chave: </b>',
    'PrizeType_Msg' => '<b>Tipo: </b>',
    'NewValue_Msg' => '<b>Novo valor: </b>',
    'NewValueNoCurrency_Msg' => '<b>Novo valor incompleto: </b>',
    'EditPrizeCurrency_Msg' => '<b>Novo valor: </b>',
    'TitleLenght_Msg' => 'O título inserido é muito curto. Por favor insira um novo com mais de 5 caracteres.',
    'ValidHashtag_Msg' => 'A hashtag inserida é inválida, por favor insira uma nova.',
    'DuplicatedHashtag_Msg' => 'A hashtag inserida já está em uso, por favor insira uma nova.',
    'HashtagSkipped_Msg' => '<b>Hashtag:</b> <i>Pulada</i>.',
    'DescriptionSkipped_Msg' => '<b>Descrição:</b> <i>sem descrição</i>.',
    'MaxparticipantsNotValid_Msg' => 'O número máximo de usuários permitidos não é válido. Por favor insira um novo.',
    'MaxparticipantsInfinite_Msg' => '<b>Máximo de membros:</b> <i>sem limites</i>.',
    'DateNotValid_Msg' => 'A data inserida não é válida, por favor insira um número entre 3-40.',
    'ValueNotValid_Msg' => 'Por favor insira um valor válido.',
    'NewValueNotValid_Msg' => 'O novo valor não é válido, por favor insira um novo.',
    'CancelGiveawayPrompt_Msg' => 'Você tem certeza que deseja cancelar a configuração deste sorteio?
Esta ação não pode ser desfeita e todos os dados inseridos serão perdidos.',
    'ShowHashtagMissing_Msg' => 'você deveria inserir a hashtag do sorteio:',
    'ClosedGiveawayWarn_Msg' => '<b>O sorteio pedido está fechado.</b>',
    'NoGiveawayWarn_Msg' => '<b>Sorteio não encontrado</b>',
    'MaxParticipants_Msg' => 'Desculpe mas o sorteio chegou ao limite de usuários.',
    'JoinedSuccess_Msg' => 'Você entrou no sorteio!',
    'CancelSuccess_Msg' => 'Você deletou o sorteio  ¯\_(ツ)_/¯',
    'MissingHashtagWarn_Msg' => 'Você deveria inserir uma hashtag:',
    'StatsEmpty_Msg' => 'Desculpe, você não se inscreveu em nenhum sorteio',
    'Value_Msg' => 'Pelo valor de ',
    'Owned_Msg' => '<code>Próprios</code>',
    'Joined_Msg' => '<code>Participando</code>',
    'Closed_Msg' => '<code>Fechado</code>',
    'LastDay_Msg' => '<code>Último dia</code>',
    'UserError_Msg' => '<b>O sorteio ou usuário pesquisado não existe.</b>',
    'AlreadyIn_Msg' => '<b>Você já entrou neste sorteio.</b>',
    'ReferralLink_Msg' => 'Este é seu link de referência, compatilhe-o com seus amigos:',
    'AfterCreation_Msg' => 'Sorteio criado com sucesso!',
    'Hash_Msg' => '<b>Hashtag: </b>',
    'Type_Msg' => '<b>Tipo: </b>',
    'MPValue_Msg' => '<b>Máximo de usuários permitidos: </b>',
    'EndDate_Msg' => '<b>Data de fim: </b>',
    'Desc_Msg' => '<b>Descrição: </b>',
    'GiveawayPrizes_Msg' => '<b>Número de prêmios: </b>',
    'Undefined_Msg' => '<i>Não definido</i>',
    'TotalValue_Msg' => '<b>Pelo valor de: </b>',
    'JoinLabel_Msg' => 'Participar ',
    'Unlimited_Msg' => '<i>Ilimitado</i>',
    'Inception_Msg' => '<b>Você criou este sorteio. Você não pode participar nele ;)</b>',
    'NowLabel_Msg' => ' agora e ganhe prêmios incríveis!',
    'UnavailableDesc_Msg' => 'Nenhuma descrição encontrada',
    'Days_Msg' => 'dias',
    'Menu_Button' => '📜 Menu',
    'Register_Button' => '🖍 Criar',
    'Show_Button' => '🕹 Navegar',
    'Language_Button' => '🌐 Linguagem',
    'standard_Button' => '➡️ JoinIn',
    'cumulative_Button' => '↪️ ShareIt',
    'Back_Button' => '🔙 Voltar',
    'Skip_Button' => '🔜 Pular',
    'Confirm_Button' => '✔️ Confirmar',
    'Infinite_Button' => '⚪️ Sem limite',
    'EditTitle_Button' => '📝 Editar título',
    'EditHashtag_Button' => '#⃣ Editar hashtag',
    'EditMaxparticipants_Button' => '🔢 Editar membros',
    'EditDescription_Button' => '📝 Editar descrição',
    'EditDate_Button' => '📅 Editar data',
    'DeleteHashtag_Button' => '❎ Deletar hashtag',
    'DeleteDescription_Button' => '❎ Deletar descrição',
    'AddHashtag_Button' => '#⃣ Adicionar hashtag',
    'AddDescription_Button' => '📝 Adicionar descrição',
    'AddMaxparticipants_Button' => '🔢 Adicionar limite de membros',
    'ConfirmGiveaway_Button' => '✔️ Confirmar',
    'ConfirmPrizes_Button' => '✔️ Confirmar prêmios',
    'AddPrize_Button' => '➕ Adicionar prêmio',
    'CancelGiveaway_Button' => '✖️ Cancelar sorteio',
    'EditPrizeName_Button' => '📝 Editar nome',
    'EditPrizeType_Button' => '🎲 Editar tipo',
    'EditPrizeValue_Button' => '💲 Editar valor',
    'EditPrizeCurrency_Button' => '💱 Editar moeda',
    'DeletePrize_Button' => '❌ Deletar',
    'Prizes_Button' => '🎁 Todos os prêmios',
    'Type1_Button' => '🎮 Chave de Video Games',
    'Type2_Button' => '📃 Coupon',
    'Type3_Button' => '📄 Gift Card',
    'Type4_Button' => '🔑 Outros',
    'Join_Button' => '#⃣ Participar',
    'Cancel_Button' => '🚫 Cancelar',
    'Help_Button' => '*⃣ Ajudar',
    'About_Button' => 'ℹ️ Sobre',
    'Source_Button' => '📖 Fonte',
    'Updates_Button' => '❕ Atualizações',
    'ClosedGiveaway_Msg' => '<b>O sorteio desejado está fechado.</b>',
    'standard_AnswerCallback' => 'JoinIn',
    'cumulative_AnswerCallback' => 'ShareIt',
    'HashtagSkipped_AnswerCallback' => 'Hashtag pulada',
    'DescriptionSkippet_AnswerCallback' => 'Sem descrição',
    'MaxparticipantsInfinite_AnswerCallback' => 'Sem limite',
    'Language_AnswerCallback' => 'Escolha linguagem:',
    '€_AnswerCallback' => 'Euro',
    '$_AnswerCallback' => 'Dollar',
    'Register_InlineQuery' => 'Registrar',
    'SwitchPM_InlineQuery' => 'Criar ou navegar',
    'ShareLink_Button' => 'Share',
    'ShowLink_Button' => 'Show link',
    'UndefinedHashtag_Msg' => '<i>No hashtag</i>',
    'BrowsePrize_Button' => 'Browse Prizes',
    'it' => 'Italiano',
    'es' => 'Espanhol',
    'fr' => 'Francês',
    'de' => 'Alemão',
    'ru' => 'Russo',
    'fa' => 'Persa',
    'hi' => 'Hindu',
    'fi' => 'Finlandês',
    'nl' => 'Holandês',
    'zh' => 'Chinês',
];
